USE [MI_Chsd2017]
GO

/****** Object:  StoredProcedure [CST].[MI_0000_MASTER_LOAD]    Script Date: 9/2/2018 1:37:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



create PROCEDURE [CST].[MI_0000_MASTER_LOAD]  
(@RR BIT=0, @TESTING BIT=0)   
AS  
BEGIN TRY  
  
DECLARE @INFO VARCHAR(8000)  
,@DB_ID INT = DB_ID()  
,@LOGID INT = 0  
,@PROC VARCHAR(500)=OBJECT_SCHEMA_NAME(@@PROCID)+'.'+OBJECT_NAME(@@PROCID)  
;  
DECLARE @PROCFULLNAME VARCHAR(500) = DB_NAME()+'.'+@PROC;  
SET @INFO = '@RR='+CAST(@RR AS CHAR(1))+', @TESTING='+CAST(@TESTING AS CHAR(1));  

EXEC SP_SET_SESSION_CONTEXT 'failure_mail_sent', 0; 
  
EXEC dbo.SP_MI_UTIL_SEND_MAIL @PROCFULLNAME, 'STARTED', 1, @ECHO=0;  
EXEC dbo.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, @INFO=@INFO, @LOG2ID=@LOGID OUT;  
  
DECLARE @RC INT;  
DECLARE @MSG VARCHAR(1000);  
  
  
EXEC @RC=DBO.MI_0001_DATE_CHECK @TESTING; IF @RC <> 0 RAISERROR ('',16,1);  
  
IF @TESTING=0 EXEC @RC=DBO.MI_0002_BUILD_INPUT_VIEWS; IF @RC <> 0 RAISERROR ('',16,1);  
  
IF @RR=1 BEGIN   
 EXEC @RC=DBO.MI_8130_FLUSH_CHECKPOINTS; IF @RC <> 0 RAISERROR ('',16,1);  
 END  
  
DECLARE @ROWCHECK INT=(SELECT COUNT(*) FROM DBO.RFT_REV_CODE WHERE REV_DESC_MAJ IS NOT NULL);  
  
DECLARE @MI_POST_DATE DATE = DBO.FN_GETMIPARM('MI POST DATE');  
EXEC @RC=DBO.MI_0005_INDEX_MANAGEMENT; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0010_PREP_FOR_LOAD @TESTING=@TESTING; IF @RC <> 0 RAISERROR ('',16,1);  
  
  
EXEC @RC=DBO.MI_0020_SCOPE_DATA; IF @RC <> 0 RAISERROR ('',16,1);  
IF @TESTING=0 OR @ROWCHECK < 50 EXEC @RC=DBO.MI_0022_CHECK_SCOPE; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0025_ANALYZE_ENROLLMENT; IF @RC <> 0 RAISERROR ('',16,1);  
IF @TESTING=0 OR @ROWCHECK < 50 EXEC @RC=DBO.MI_0040_UPDATE_INDUSTRY_CODES; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0090_PREP_CLAIMLINE; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0095_PREP_ENROLLMENT; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0100_PRE_LOAD_VALIDATIONS; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0150_LOAD_DIM_MEMBER; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0151_PROCESS_PERSON_IDENTIFICATION; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0200_LOAD_SMALL_DIMENSIONS; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0205_LOAD_DIM_PROVIDER; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0206_BUILD_PROVIDER_CROSSWALK; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0207_BUILD_DISTINCT_PROVIDER_TABLE; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0210_LOAD_DIM_GROUP; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0230_LOAD_DIM_BENEFIT; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0250_PRE_FACT_LOAD_VALIDATIONS; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0300_LOAD_FACT_ENROLLMENT; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0310_LOAD_FACT_MEMBER_MONTHS; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0311_GROUP_CONSOLIDATE; IF @RC <> 0 RAISERROR ('',16,1); 
EXEC @RC=DBO.MI_0319_BENCHMARK_SLICE; IF @RC <> 0 RAISERROR ('',16,1);  
  
EXEC @RC=DBO.MI_0330_LOAD_FACT_AUTH; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0335_LOAD_FACT_ADMIN; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0340_LOAD_FACT_CAP; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0350_LOAD_FACT_PREM; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0400_LOAD_FACT_SERVICES; IF @RC <> 0 RAISERROR ('',16,1);
EXEC @RC=DBO.MI_0401_ENABLE_SERVICES_INDEXES; IF @RC <> 0 RAISERROR ('',16,1);
IF COALESCE(DBO.FN_GETMIPARM('ENABLE DISCOUNT CST CONFIG'),'YES')='YES'    
 EXEC @RC=CST.MI_7011_DEFAULT_DISCOUNT_CALC; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0220_LOAD_DOMESTIC_BRIDGE; IF @RC <> 0 RAISERROR ('',16,1);  
  
EXEC @RC=DBO.MI_0402_APPLY_ROW_SECURITY_KEYS; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0405_BUILD_LIMIT_TABLES; IF @RC <> 0 RAISERROR ('',16,1);  
  
--HCG Grouping - common input files for MI groupers  
--cleaned up later in MI_0509_GROUP_HCG_INPUT_CLEANUP
EXEC @RC=DBO.MI_0509_GROUP_HCG_INPUT_TABLES; IF @RC <> 0 RAISERROR ('',16,1);
EXEC @RC=DBO.MI_0509_GROUP_HCG_INPUT_FILES; IF @RC <> 0 RAISERROR ('',16,1);  

DECLARE @HCG_GROUPER_YEAR AS CHAR(4) = COALESCE(DBO.FN_GETMIPARM('HCG CODE SETS YEAR'),'2018');
 
IF @HCG_GROUPER_YEAR = '2017'   
BEGIN   
 EXEC @RC=DBO.MI_0509_GROUP_HCG_2017; IF @RC <> 0 RAISERROR ('',16,1);   
END  
IF @HCG_GROUPER_YEAR = '2018'   
BEGIN   
 EXEC @RC=DBO.MI_0509_GROUP_HCG_2018; IF @RC <> 0 RAISERROR ('',16,1);   
END  
IF @HCG_GROUPER_YEAR = '2019'   
BEGIN   
 EXEC @RC=DBO.MI_0509_GROUP_HCG_2019; IF @RC <> 0 RAISERROR ('',16,1);   
END  
  
  
  
EXEC @RC=DBO.MI_0511_VALIDATE_HCG; IF @RC <> 0 RAISERROR ('',16,1);  
  
--DRG Grouping  
EXEC @RC=DBO.MI_0500_GROUP_DRG; IF @RC <> 0 RAISERROR ('',16,1);  
  
EXEC @RC=DBO.MI_0513_REPROCESS_CLAIMS_LINKAGE; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0515_CLAIMS_GAP_FILL; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0520_CALC_IBNR; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0530_GROUP_ETG_ERG; IF @RC <> 0 RAISERROR ('',16,1);  
--EXEC @RC=DBO.MI_0570_GROUP_MEG; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=CST.MI_0541_CALC_MARA_JAVA; IF @RC <> 0 RAISERROR ('',16,1); 


 
EXEC @RC=DBO.MI_0550_GROUP_CCHG_SQL; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0555_WC_LOAD; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0570_GROUP_CMSHCC; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0320_CREATE_BENCHMARKS; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0560_GLOBALRVU; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0650_PHARMACY_ANALYSIS; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0440_RUN_ATTRIBUTION; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0699_RI_TESTING; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0800_MEASURES; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0325_CREATE_ADMIN_BENCHMARKS; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_1000_INDEX_MANAGEMENT; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_9100_BUILD_CLIENT_BASE_VIEWS; IF @RC <> 0 RAISERROR ('',16,1);  
--EXEC @RC=DBO.MI_9110_REFRESH_ROW_SECURITY; IF @RC <> 0 RAISERROR ('',16,1);  

--EXEC @RC=DBO.MI_0509_GROUP_HCG_INPUT_CLEANUP; IF @RC <> 0 RAISERROR ('',16,1);

IF COALESCE(DBO.FN_GETMIPARM('EBM ENABLED'),'NO') = 'YES' AND   
 EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='EBM' AND ROUTINE_NAME='1000_EBM_ENGINE')  
 BEGIN  
 EXEC @RC=EBM.[1000_EBM_ENGINE] @TESTING=@TESTING; IF @RC <> 0 RAISERROR ('',16,1);  
 END  
EXEC @RC=DBO.MI_0910_RUN_CLAIMAUDIT; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0920_RUN_MI65_OPP; IF @RC <> 0 RAISERROR ('',16,1);  
  
IF COALESCE(DBO.FN_GETMIPARM('ACO ENABLED'),'NO')='YES' BEGIN  
 IF NOT EXISTS (SELECT * FROM SYS.PROCEDURES WHERE SCHEMA_NAME(SCHEMA_ID)='ACO') RAISERROR('',11,252)  
 EXEC @RC=[ACO].[RUN_ACO_LOGIC]; IF @RC <> 0 RAISERROR ('',16,1);  
END   
EXEC @RC=DBO.MI_6001_VALIDATE_BENCHMARKS; IF @RC <> 0 RAISERROR ('',16,1);  
IF @TESTING=0   
 EXEC @RC=DBO.MI_5000_AUTO_MAINTENANCE; IF @RC <> 0 RAISERROR ('',16,1);  
EXEC @RC=DBO.MI_0700_RECON_RUN; IF @RC <> 0 RAISERROR ('',16,1);  
  
EXEC @RC=DBO.MI_8140_SET_SIGNATURE @SET=1; IF @RC <> 0 RAISERROR ('',16,1)  
EXEC @RC=DBO.MI_1099_CLEANUP; IF @RC <> 0 RAISERROR ('',16,1);  
  

IF @TESTING=0   
 EXEC @RC=DBO.MI_1100_AUTO_COPY; IF @RC <> 0 RAISERROR ('',16,1);  
  
EXEC @RC=DBO.MI_8900_RUN_CUSTOM_CODE @PROC; IF @RC <> 0 RAISERROR ('',16,1);  

EXEC @RC=DBO.MI_8130_FLUSH_CHECKPOINTS; IF @RC <> 0 RAISERROR ('',16,1);  
  


EXEC [DBO].[MI_8131_SET_MI_PROCESSING_COMPLETE_EXTENDED_PROPERTY];  
  
  
EXEC dbo.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, @LOG2ID=@LOGID, @END_FLAG=1;  
EXEC dbo.SP_MI_UTIL_SEND_MAIL @PROCFULLNAME, 'COMPLETED', 1, @ECHO=0;  
  
END TRY  
BEGIN CATCH  
 IF ERROR_STATE() = 255 BEGIN  
  SET @MSG='**** DEVELOPMENT MODE HALT'+CHAR(10)+  
     '    TO CONTINUE, EXECUTE MI_0000 AGAIN.  TO RUN FROM THE BEGINING EXECUTE MI_0000 WITH THE "1" PARM.'+CHAR(10);  
     --'  TO DISABLE THIS DEV HALT, EXECUTE:'+CHAR(10)+CHAR(10)+  
     --'  EXEC UTIL_SETMIPARM ''DEVELOPMENT OR PRODUCTION MODE'',''PROD''';  
  EXEC DBO.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, @MSG, @LOG2ID=@LOGID;  
  RETURN 0;  
  END  
 ELSE IF ERROR_STATE() = 252 BEGIN  
  SET @MSG='**** INSTALL ACO COMPONENT, OR DISABLE ACO OPTION'+CHAR(10)+  
     '     EXEC DBO.UTIL_SETMIPARM ''ACO ENABLED'',''NO''';  
  EXEC DBO.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, @MSG, @LOG2ID=@LOGID;  
  RETURN 0;  
  END  
 ELSE BEGIN  
  SET @MSG = 'HALTED - ' + dbo.FN_MI_UTIL_GET_ERROR_STRING();  
  EXEC DBO.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, @MSG, @LOG2ID=@LOGID;  
  RAISERROR(@MSG,16,1)  
  RETURN 16;  
  END  
 END CATCH  
  
  
  
--$LastChangedDate: 2018-08-09 07:52:58 -0700 (Thu, 09 Aug 2018) $  
--$LastChangedRevision: 44869 $  
--$Author: ssamario $  
--$HeadURL: https://topsvcs.medinsight.milliman.com/svn/MedInsight/branches/Database/MI_12/MI/Schema%20Objects/Schemas/dbo/Programmability/Stored%20Procedures/MI_0000_MASTER_LOAD.proc.sql $   
 
GO


