USE [MI_CHSD2016]
GO

/****** Object:  StoredProcedure [CST].[CONSOLIDATE_04_EBM_KEYS]    Script Date: 3/7/2018 8:02:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [CST].[CONSOLIDATE_04_EBM_KEYS]
	@DB_NAME VARCHAR(50),
	@CID VARCHAR(2)
AS

SET NOCOUNT ON

DECLARE @SQL VARCHAR(4000)
SET @SQL = 'EBM KEYS STARTED from ' + @DB_NAME
raiserror (@SQL, 10,1) with nowait

EXEC('
exec sp_mi_droptable ''#TEMP_MEMBER_S''
SELECT
	MEMBER_KEY,
	'''+@CID + '-'' + COALESCE(MEMBER_ID,'''') AS MEMBER_ID,
	MEM_START_DATE,
	MEM_END_DATE
INTO #TEMP_MEMBER_S
FROM ' + @DB_NAME + '.dbo.MEMBER

exec sp_mi_droptable ''#TEMP_MEMBER_T''
SELECT
	MEMBER_KEY,
	MEMBER_ID,
	MEM_START_DATE,
	MEM_END_DATE
INTO #TEMP_MEMBER_T
FROM MEMBER

CREATE UNIQUE CLUSTERED INDEX XPK ON #TEMP_MEMBER_S(MEMBER_ID,MEM_START_DATE,MEM_END_DATE)
CREATE UNIQUE CLUSTERED INDEX XPK ON #TEMP_MEMBER_T(MEMBER_ID,MEM_START_DATE,MEM_END_DATE)

exec sp_mi_droptable ''##MEMBER''
SELECT 
	S.MEMBER_KEY AS S_MEMBER_KEY,
	COALESCE(T.MEMBER_KEY,0) AS T_MEMBER_KEY,
	S.MEMBER_ID AS S_MEMBER_ID,
	T.MEMBER_ID AS T_MEMBER_ID
INTO ##MEMBER
FROM #TEMP_MEMBER_S S
	LEFT JOIN #TEMP_MEMBER_T T 
		ON S.MEMBER_ID = T.MEMBER_ID AND S.MEM_START_DATE = T.MEM_START_DATE
			AND S.MEM_END_DATE = T.MEM_END_DATE

CREATE UNIQUE CLUSTERED INDEX XPK ON ##MEMBER(S_MEMBER_KEY)
WITH (IGNORE_DUP_KEY = ON)

INSERT INTO ##MEMBER
SELECT 0 AS S_MEMBER_KEY,0 AS T_MEMBER_KEY,S.MEMBER_ID AS S_MEMBER_ID,S.MEMBER_ID AS T_MEMBER_ID
FROM #TEMP_MEMBER_S S WHERE MEMBER_KEY = 0

exec sp_mi_droptable ''##EBM_DATES''
SELECT DISTINCT
	ENDING_MONTH
INTO ##EBM_DATES
FROM ' + @DB_NAME + '.EBM.EBM_DETAIL S
WHERE CI_MEASURE_ID <> ''NOEBM''

exec sp_mi_droptable ''##RFT_PERSON_ID''
SELECT
	S.PERSON_KEY AS S_PERSON_KEY,
	T.PERSON_KEY AS T_PERSON_KEY,
	S.PERSON_ID AS S_PERSON_ID,
	T.PERSON_ID AS T_PERSON_ID
INTO ##RFT_PERSON_ID
FROM ' + @DB_NAME + '.dbo.RFT_PERSON_ID S
	LEFT JOIN RFT_PERSON_ID T 
		ON S.PERSON_ID + ''-' + @CID + ''' = T.PERSON_ID 
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_PERSON_ID(S_PERSON_KEY)
WITH (IGNORE_DUP_KEY = ON)
INSERT INTO ##RFT_PERSON_ID SELECT 0,0,NULL,NULL

exec sp_mi_droptable ''##MEMBER_MONTH''
SELECT
	S.MEMBER_MONTH_KEY AS S_MEMBER_MONTH_KEY,
	T.MEMBER_MONTH_KEY AS T_MEMBER_MONTH_KEY
INTO ##MEMBER_MONTH
FROM ' + @DB_NAME + '.dbo.MEMBER_MONTH S
	INNER JOIN ##MEMBER M ON S.MEMBER_KEY = M.S_MEMBER_KEY
	INNER JOIN ##RFT_PROD_TYPE PR ON S.PROD_TYPE_KEY = PR.S_PROD_TYPE_KEY
	INNER JOIN MEMBER_MONTH T
		ON S.MEMBER_MONTH_START_DATE = T.MEMBER_MONTH_START_DATE
		AND M.T_MEMBER_KEY = T.MEMBER_KEY
		AND S.EFF_DATE = T.EFF_DATE
		AND S.TERM_DATE = T.TERM_DATE
		AND PR.T_PROD_TYPE_KEY = T.PROD_TYPE_KEY
		AND S.MI_POST_DATE = T.MI_POST_DATE
	INNER JOIN ##EBM_DATES D ON S.MEMBER_MONTH_START_DATE = D.ENDING_MONTH
CREATE UNIQUE CLUSTERED INDEX XPK ON ##MEMBER_MONTH(S_MEMBER_MONTH_KEY)

')

SET @SQL = 'EBM KEYS CREATED from ' + @DB_NAME
raiserror (@SQL, 10,1) with nowait



GO


