

/****** Object:  StoredProcedure [dbo].[MI_8021_MI_HCG_INPUT_TABLES_MED]    Script Date: 7/30/2018 11:04:15 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [CST].[MI_8021_MI_HCG_INPUT_TABLES_MED]
AS
BEGIN

	DECLARE @DB_ID INT = DB_ID()
	,@LOGID INT = 0
	,@PROC VARCHAR(500)=OBJECT_SCHEMA_NAME(@@PROCID)+'.'+OBJECT_NAME(@@PROCID)
	,@PERF_START datetime
	,@PERF_DURATION int
	,@PERF_ROW INT
	,@RC INT
	,@MSG VARCHAR(1000);

	EXEC dbo.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, @LOG2ID=@LOGID OUT;
	DECLARE @MI_POST_DATE DATE=COALESCE(DBO.FN_GETMIPARM('MI POST DATE'),'TRAP');

	DECLARE @DRGPREF VARCHAR(20); SET @DRGPREF=COALESCE(DBO.FN_GETMIPARM('PREFERRED DRG'),'MS')
	DECLARE @DRGPRIOR VARCHAR(20); SET @DRGPRIOR =COALESCE(DBO.FN_GETMIPARM('DRG PRIORITY'),'MI')
	DECLARE @UTILFORDENIED CHAR(3); SET @UTILFORDENIED  =COALESCE(DBO.FN_GETMIPARM('COUNT UTILS FOR DENIED CLAIM LINES'),'NO')
	DECLARE @HCGCWBPROV CHAR(3); SET @HCGCWBPROV  =COALESCE(DBO.FN_GETMIPARM('HCG USE CROSSWALKED BILL PROV'),'YES')

	
	--Create INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1 table. 
	SET @PERF_START = GETDATE();
	EXEC DBO.SP_MI_DROPTABLE 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1'

	SELECT		S.SERVICE_MONTH_START_DATE
				,S.CLAIM_ID_KEY
				,S.SERVICES_KEY
				,S.MI_POST_DATE
				,CONVERT(VARCHAR(10), M.MEM_DOB, 101) AS DATEOFBIRTH
				,M.MEM_GENDER AS GENDER
				,CASE WHEN MX.CONTRACT_KEY IS NOT NULL THEN 'C' WHEN SKL.PROXY_SUBSCRIBER_KEY IS NOT NULL AND SKL.PROXY_SUBSCRIBER_KEY <> 0 THEN 'S' ELSE 'M' END + right(replicate('0',19) + CAST(CASE WHEN MX.CONTRACT_KEY IS NOT NULL THEN COALESCE(CG.CLAIM_ID_KEY_GROUP, S.CLAIM_ID_KEY) WHEN SKL.PROXY_SUBSCRIBER_KEY IS NOT NULL AND SKL.PROXY_SUBSCRIBER_KEY <> 0  THEN SKL.PROXY_SUBSCRIBER_KEY ELSE COALESCE(SKL.MI_PERSON_KEY, S.MI_PERSON_KEY) END AS VARCHAR),19)  AS CONTRACTID
				,COALESCE(SKL.MI_PERSON_KEY, S.MI_PERSON_KEY)  as MemberId
				,coalesce(CG.CLAIM_ID_KEY_GROUP, S.CLAIM_ID_KEY) as ClaimId
	INTO		DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1
	FROM		DBO.SERVICES S
	LEFT JOIN	DBO.MEMBER M ON S.MEMBER_KEY = M.MEMBER_KEY	
	LEFT JOIN	DBO.RFT_CLAIM_ID_GROUP CG ON S.SERVICES_KEY = CG.SERVICES_KEY
	LEFT JOIN	DBO.HCG_PERSON_KEY_PROXY_SUBSCRIBER_KEY_LOOKUP SKL ON S.MEMBER_KEY = SKL.MEMBER_KEY
	LEFT JOIN	DBO.SERVICES_RX RX ON S.[SERVICE_MONTH_START_DATE]=RX.[SERVICE_MONTH_START_DATE] AND S.[CLAIM_ID_KEY] = RX.[CLAIM_ID_KEY] AND S.[SERVICES_KEY] = RX.[SERVICES_KEY] AND S.[MI_POST_DATE] = RX.[MI_POST_DATE] 
	LEFT JOIN	DBO.RFT_MRLINE_TAB MR ON S.MR_LINE_KEY = MR.MR_LINE_KEY
	LEFT JOIN	DBO.SUBSCRIBER_EXCEEDS_MAXIMUM_RECORD_COUNT MX ON  MX.CONTRACT_KEY = case when s.Subscriber_Key <> 0 then s.Subscriber_Key else s.MEMBER_KEY end and MX.IS_SUBSCRIBER_KEY = case when s.Subscriber_Key <> 0 then 1 else 0 end
	WHERE RX.[SERVICE_MONTH_START_DATE] IS NULL --EXCLUDE PHARMACY CLAIMS

	SET @PERF_ROW=@@ROWCOUNT;
	SET @PERF_DURATION = DATEDIFF(minute,@PERF_START,GETDATE())
	EXEC dbo.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1 LOADED', @PERF_ROW, @DURATION_IN_MIN=@PERF_DURATION, @LOG2ID=@LOGID;
		
	--CCI_INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1 TABLE QUERIED MULTIPLE TIMES AND SO ADDING CCI TO IT
	SET @PERF_START = GETDATE();
	CREATE CLUSTERED COLUMNSTORE INDEX CCI_INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1 ON DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1;  
	SET @PERF_DURATION = DATEDIFF(minute,@PERF_START,GETDATE());
	SET @MSG='DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1: CREATE CLUSTERED COLUMNSTORE INDEX: '+CONVERT(VARCHAR(12),@PERF_ROW)+' ELAPSED TIME: '+CONVERT(VARCHAR(12),@PERF_DURATION);
	EXEC dbo.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, @MSG, 0, @DURATION_IN_MIN=@PERF_DURATION, @LOG2ID=@LOGID;


	--CREATE INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP2 TABLE. 
	SET @PERF_START = GETDATE();
	EXEC DBO.SP_MI_DROPTABLE 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP2'

	SELECT		
				S.SERVICE_MONTH_START_DATE AS SERVICE_MONTH_START_DATE
				,S.SERVICES_KEY AS SERVICES_KEY
				,S.CLAIM_ID_KEY AS CLAIM_ID_KEY
				,S.MI_POST_DATE AS MI_POST_DATE
				,S.SERVICES_KEY AS  SequenceNumber
				,CAST(CASE WHEN S.SV_LINE > 999 THEN 999 ELSE S.SV_LINE END AS VARCHAR(3)) AS LineNumber
				,K.DateOfBirth
				,K.Gender
				,K.MemberId
				,K.CONTRACTID
				,K.ClaimId
				,CONVERT(VARCHAR(10), S.FROM_DATE, 101) AS FromDate
				,CONVERT(VARCHAR(10), S.TO_DATE, 101) AS ToDate
				,CONVERT(VARCHAR(10), S.PAID_DATE, 101) AS PaidDate
				,CONVERT(VARCHAR(5), CASE WHEN PRC.PROC_CODE_KEY=0 THEN NULL ELSE PRC.PROC_CODE END) AS HCPCS
				,CONVERT(VARCHAR(2),CASE WHEN S.PROC_MOD1_KEY=0 THEN NULL ELSE COALESCE(MD.HCG_MOD,MD.CPT_MOD) END) AS ModifierCode1
				,NULL AS SourcePlaceOfService
				,CONVERT(CHAR(2), CASE WHEN PT.POS_KEY = 0 THEN NULL ELSE PT.POS END) AS PlaceOfService
				,NULL AS SourceSpecialty
				,CONVERT(CHAR(2), COALESCE(TX.MILLIMAN_SPECIALTY, NULL)) AS Specialty
				,_CLAIM_UDF_09_ AS EncounterFlag			
				,CONVERT(VARCHAR(40),
							CASE WHEN @HCGCWBPROV='YES' THEN
							CASE WHEN P1.PROV_CW_KEY=0 THEN NULL ELSE P1.PROV_CW_KEY END
							ELSE CASE WHEN S.BILL_PROV_KEY=0 THEN NULL ELSE S.BILL_PROV_KEY END END) AS ProviderId
				,PROV_CLINIC_ZIP AS ProviderZip
				,NULL AS ProviderCounty
				,NULL AS MedicareId
				,S.AMT_BILLED AS BILLED
				,S.AMT_ALLOWED AS ALLOWED
				-- LW 7/30/18,
				--CASE 
				--	WHEN SV_STAT='D' THEN
				--		CASE WHEN @UTILFORDENIED='YES' THEN COALESCE(NULLIF(S.AMT_BILLED,0),0.01*SIGN(COALESCE(NULLIF(S.AMT_ALLOWED,0),NULLIF(S.AMT_PAID,0),1))) 
				---				ELSE S.AMT_BILLED END 
				--	ELSE S.AMT_BILLED
				--	END
				--	AS BILLED
				--,CASE 
				---	WHEN SV_STAT='D' THEN
				--		CASE WHEN @UTILFORDENIED='YES' THEN COALESCE(NULLIF(S.AMT_ALLOWED,0),0.01*SIGN(COALESCE(NULLIF(S.AMT_BILLED,0),NULLIF(S.AMT_PAID,0),1))) 
				--				ELSE S.AMT_ALLOWED END 
				--	ELSE S.AMT_ALLOWED
				--	END
				--	AS ALLOWED
				,S.AMT_PAID AS Paid
				,S.AMT_COB AS COB
				,S.AMT_COPAY AS CoPay
				,S.AMT_COINS AS CoInsurance
				,S.AMT_DEDUCT AS Deductable
				,_CLAIM_UDF_41_ AS PATIENTPAY
				,S.SV_UNITS AS UNITS
				--,CONVERT(NUMERIC(8,0),CASE WHEN ABS(COALESCE(S.SV_UNITS,0)) <= 32767 THEN CONVERT(NUMERIC(8,0),COALESCE(S.SV_UNITS,0)) ELSE 32767*SIGN(COALESCE(S.SV_UNITS,0)) END) AS UNITS
				,CASE WHEN I1.ICD_10_OR_HIGHER = 0 THEN '9' ELSE '10' END  AS ICDVERSION 
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_01_KEY = 0 THEN NULL ELSE I1.ICD_DIAG END) AS ICD_DIAG_01
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_02_KEY = 0 THEN NULL ELSE I2.ICD_DIAG END) AS ICD_DIAG_02
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_03_KEY = 0 THEN NULL ELSE I3.ICD_DIAG END) AS ICD_DIAG_03
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_04_KEY = 0 THEN NULL ELSE I4.ICD_DIAG END) AS ICD_DIAG_04		
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_05_KEY = 0 THEN NULL ELSE I5.ICD_DIAG END) AS ICD_DIAG_05		
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_06_KEY = 0 THEN NULL ELSE I6.ICD_DIAG END) AS ICD_DIAG_06		
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_07_KEY = 0 THEN NULL ELSE I7.ICD_DIAG END) AS ICD_DIAG_07		
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_08_KEY = 0 THEN NULL ELSE I8.ICD_DIAG END) AS ICD_DIAG_08		
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_09_KEY = 0 THEN NULL ELSE I9.ICD_DIAG END) AS ICD_DIAG_09	
				,CONVERT(VARCHAR(7),CASE WHEN S.ICD_DIAG_10_KEY = 0 THEN NULL ELSE I10.ICD_DIAG END) AS ICD_DIAG_10
				,NULL AS RiskPool
				,_CLAIM_UDF_10_ AS OON
				--LW 7/30 ,CASE WHEN S.SV_STAT IN ('P', 'D', 'E', 'R') THEN S.SV_STAT ELSE NULL END AS CLAIM_LINE_STATUS
				,_CLAIM_UDF_31_ AS CLAIM_LINE_STATUS
				,_CLAIM_UDF_45_ AS CURRENTALLOWED
				,NULL AS SRCLOB
				,NULL AS LOB
				,NULL AS SRCPRODUCT
				,NULL AS PRODUCT
				,NULL AS GROUPID
				,NULL AS ZIP
				,NULL AS COUNTY
				,NULL AS MEMBERSTATUS
				,NULL AS USERDEFPOP1
				,NULL AS USERDEFPOP2
				,NULL AS USERDEFPOP3
				,NULL AS USERDEFNUM1
				,NULL AS USERDEFNUM2
				,NULL AS USERDEFNUM3				
	INTO		DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP2
	FROM 		DBO.SERVICES S
	INNER JOIN	DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1 K ON S.SERVICE_MONTH_START_DATE=K.SERVICE_MONTH_START_DATE AND S.CLAIM_ID_KEY = K.CLAIM_ID_KEY AND S.SERVICES_KEY = K.SERVICES_KEY AND S.MI_POST_DATE = K.MI_POST_DATE
	LEFT JOIN	DBO.RFT_PROC_CODE PRC ON S.PROC_CODE_KEY = PRC.PROC_CODE_KEY		
	LEFT JOIN	DBO.PROVIDER P1 ON S.BILL_PROV_KEY = P1.PROV_KEY
	LEFT JOIN	DBO.PROVIDER P2 ON S.ATT_PROV_KEY = P2.PROV_KEY
	LEFT JOIN	DBO.RFT_PROV_TAXONOMY TX ON P2.PROV_TAXONOMY = TX.TAXONOMY_CODE
	-- LW 7/30 ADDED SERVICES UDF AND PROVIDER CLINIC TABLES
	LEFT JOIN   DBO.PROVIDER_CLINIC P3 ON P2.PROV_CLINIC_KEY = P3.PROV_CLINIC_KEY
	LEFT JOIN   DBO.SERVICES_UDF UDF ON UDF.SERVICES_KEY = S.SERVICES_KEY 
	LEFT JOIN	DBO.RFT_ICD_DIAG I1 ON S.ICD_DIAG_01_KEY = I1.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I2 ON S.ICD_DIAG_02_KEY = I2.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I3 ON S.ICD_DIAG_03_KEY = I3.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I4 ON S.ICD_DIAG_04_KEY = I4.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I5 ON S.ICD_DIAG_05_KEY = I5.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I6 ON S.ICD_DIAG_06_KEY = I6.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I7 ON S.ICD_DIAG_07_KEY = I7.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I8 ON S.ICD_DIAG_08_KEY = I8.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I9 ON S.ICD_DIAG_09_KEY = I9.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I10 ON S.ICD_DIAG_10_KEY = I10.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_PROC_CODE PC ON S.PROC_CODE_KEY = PC.PROC_CODE_KEY 
	LEFT JOIN	DBO.RFT_CPT_MOD MD ON S.PROC_MOD1_KEY = MD.CPT_MOD_KEY
	LEFT JOIN	DBO.RFT_POS PT ON S.POS_KEY = PT.POS_KEY

	SET @PERF_ROW=@@ROWCOUNT;
	SET @PERF_DURATION = DATEDIFF(MINUTE,@PERF_START,GETDATE())
	EXEC DBO.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP2 LOADED', @PERF_ROW, @DURATION_IN_MIN=@PERF_DURATION, @LOG2ID=@LOGID;

	--CREATE INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP3 TABLE. 
	SET @PERF_START = GETDATE();
	EXEC DBO.SP_MI_DROPTABLE 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP3'
	
	select		K.SERVICE_MONTH_START_DATE
				,K.SERVICES_KEY
				,K.CLAIM_ID_KEY
				,K.MI_POST_DATE
				,convert(varchar(2),CASE WHEN S2.PROC_MOD2_KEY=0 THEN NULL ELSE coalesce(MD2.HCG_MOD,MD2.CPT_MOD) END) AS ModifierCode2
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_ADMIT_KEY = 0 THEN NULL ELSE I0.ICD_DIAG END) as AdmitDiag 
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_11_KEY = 0 THEN NULL ELSE I11.ICD_DIAG END) AS ICDDiag11
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_12_KEY = 0 THEN NULL ELSE I12.ICD_DIAG END) AS ICDDiag12
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_13_KEY = 0 THEN NULL ELSE I13.ICD_DIAG END) AS ICDDiag13
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_14_KEY = 0 THEN NULL ELSE I14.ICD_DIAG END) AS ICDDiag14
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_15_KEY = 0 THEN NULL ELSE I15.ICD_DIAG END) AS ICDDiag15
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_16_KEY = 0 THEN NULL ELSE I16.ICD_DIAG END) AS ICDDiag16
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_17_KEY = 0 THEN NULL ELSE I17.ICD_DIAG END) AS ICDDiag17
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_18_KEY = 0 THEN NULL ELSE I18.ICD_DIAG END) AS ICDDiag18
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_19_KEY = 0 THEN NULL ELSE I19.ICD_DIAG END) AS ICDDiag19
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_20_KEY = 0 THEN NULL ELSE I20.ICD_DIAG END) AS ICDDiag20
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_21_KEY = 0 THEN NULL ELSE I21.ICD_DIAG END) AS ICDDiag21
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_22_KEY = 0 THEN NULL ELSE I22.ICD_DIAG END) AS ICDDiag22
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_23_KEY = 0 THEN NULL ELSE I23.ICD_DIAG END) AS ICDDiag23
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_24_KEY = 0 THEN NULL ELSE I24.ICD_DIAG END) AS ICDDiag24
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_25_KEY = 0 THEN NULL ELSE I25.ICD_DIAG END) AS ICDDiag25
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_26_KEY = 0 THEN NULL ELSE I26.ICD_DIAG END) AS ICDDiag26
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_27_KEY = 0 THEN NULL ELSE I27.ICD_DIAG END) AS ICDDiag27
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_28_KEY = 0 THEN NULL ELSE I28.ICD_DIAG END) AS ICDDiag28
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_29_KEY = 0 THEN NULL ELSE I29.ICD_DIAG END) AS ICDDiag29
				,CONVERT(varchar(7),CASE WHEN S2.ICD_DIAG_30_KEY = 0 THEN NULL ELSE I30.ICD_DIAG END) AS ICDDiag30
				,S2.ICD_DIAG_01_POA as POA1
				,S2.ICD_DIAG_02_POA as POA2
				,S2.ICD_DIAG_03_POA as POA3
				,S2.ICD_DIAG_04_POA as POA4
				,S2.ICD_DIAG_05_POA as POA5
				,S2.ICD_DIAG_06_POA as POA6
				,S2.ICD_DIAG_07_POA as POA7
				,S2.ICD_DIAG_08_POA as POA8
				,S2.ICD_DIAG_09_POA as POA9
				,S2.ICD_DIAG_10_POA as POA10
				,S2.ICD_DIAG_11_POA as POA11
				,S2.ICD_DIAG_12_POA as POA12
				,S2.ICD_DIAG_13_POA as POA13
				,S2.ICD_DIAG_14_POA as POA14
				,S2.ICD_DIAG_15_POA as POA15
				,S2.ICD_DIAG_16_POA as POA16
				,S2.ICD_DIAG_17_POA as POA17
				,S2.ICD_DIAG_18_POA as POA18
				,S2.ICD_DIAG_19_POA as POA19
				,S2.ICD_DIAG_20_POA as POA20
				,S2.ICD_DIAG_21_POA as POA21
				,S2.ICD_DIAG_22_POA as POA22
				,S2.ICD_DIAG_23_POA as POA23
				,S2.ICD_DIAG_24_POA as POA24
				,S2.ICD_DIAG_25_POA as POA25
				,S2.ICD_DIAG_26_POA as POA26
				,S2.ICD_DIAG_27_POA as POA27
				,S2.ICD_DIAG_28_POA as POA28
				,S2.ICD_DIAG_29_POA as POA29
				,S2.ICD_DIAG_30_POA as POA30
				,s2.LOINC as LOINC
	INTO		DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP3
	FROM		dbo.SERVICES_2 S2
	INNER JOIN	DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1 K ON S2.SERVICE_MONTH_START_DATE=K.SERVICE_MONTH_START_DATE AND S2.CLAIM_ID_KEY = K.CLAIM_ID_KEY AND S2.SERVICES_KEY = K.SERVICES_KEY AND S2.MI_POST_DATE = K.MI_POST_DATE
	LEFT JOIN	DBO.RFT_ICD_DIAG I0 ON S2.ICD_DIAG_ADMIT_KEY = I0.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I11 ON S2.ICD_DIAG_11_KEY = I11.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I12 ON S2.ICD_DIAG_12_KEY = I12.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I13 ON S2.ICD_DIAG_13_KEY = I13.ICD_DIAG_KEY		
	LEFT JOIN	DBO.RFT_ICD_DIAG I14 ON S2.ICD_DIAG_14_KEY = I14.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I15 ON S2.ICD_DIAG_15_KEY = I15.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I16 ON S2.ICD_DIAG_16_KEY = I16.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I17 ON S2.ICD_DIAG_17_KEY = I17.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I18 ON S2.ICD_DIAG_18_KEY = I18.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I19 ON S2.ICD_DIAG_19_KEY = I19.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I20 ON S2.ICD_DIAG_20_KEY = I20.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I21 ON S2.ICD_DIAG_21_KEY = I21.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I22 ON S2.ICD_DIAG_22_KEY = I22.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I23 ON S2.ICD_DIAG_23_KEY = I23.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I24 ON S2.ICD_DIAG_24_KEY = I24.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I25 ON S2.ICD_DIAG_25_KEY = I25.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I26 ON S2.ICD_DIAG_26_KEY = I26.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I27 ON S2.ICD_DIAG_27_KEY = I27.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I28 ON S2.ICD_DIAG_28_KEY = I28.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I29 ON S2.ICD_DIAG_29_KEY = I29.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_ICD_DIAG I30 ON S2.ICD_DIAG_30_KEY = I30.ICD_DIAG_KEY
	LEFT JOIN	DBO.RFT_CPT_MOD MD2 ON S2.PROC_MOD2_KEY = MD2.CPT_MOD_KEY

	SET @PERF_ROW=@@ROWCOUNT;
	SET @PERF_DURATION = DATEDIFF(minute,@PERF_START,GETDATE())
	EXEC dbo.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP3 LOADED', @PERF_ROW, @DURATION_IN_MIN=@PERF_DURATION, @LOG2ID=@LOGID;

	
	--CREATE INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP4 TABLE. 
	SET @PERF_START = GETDATE();
	EXEC DBO.SP_MI_DROPTABLE 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP4'
	
	SELECT		K.SERVICE_MONTH_START_DATE
				,K.SERVICES_KEY
				,K.CLAIM_ID_KEY
				,K.MI_POST_DATE
				,convert(varchar(10), su.Adm_Date, 101) as AdmitDate
				,convert(varchar(10), su.Dis_Date, 101) as DischargeDate
				,case when DRG.DRG_Code is null OR DRG.DRG_KEY=0 or DRG.DRG_Code = '0' or len(DRG.DRG_CODE) > 3 then NULL else Right(Replicate('0',3) + rtrim(DRG.DRG_Code),3) end as DRG
				,case when DRG.DRG_KEY is null or DRG.DRG_KEY = 0 or DRG.DRG_Code = '0'  then NULL when @DRGPREF = 'MS' or @DRGPREF = 'TRI' or @DRGPREF = 'AP' or @DRGPREF = 'APR' then @DRGPREF  else NULL end as DRGVersion
				,case when rv.REV_CODE is null or rv.rev_code_key = 0 or len(rv.REV_CODE) = 0 then NULL else Right(Replicate('0',4) + rtrim(rv.REV_CODE), 4) end as RevenueCode
				,convert(varchar(3), case when rubt.UB_BILL_TYPE_KEY=0 or rubt.UB_BILL_TYPE_KEY is null THEN NULL ELSE rubt.UB_BILL_TYPE END) as BillType 
				,convert(varchar(3), CASE WHEN ras.ADM_SRC_KEY=0 or ras.ADM_SRC_KEY is null THEN NULL ELSE ras.ADM_SRC END) as AdmitSource 			
				,convert(varchar(1), CASE WHEN rat.ADM_TYPE_KEY=0 or rat.ADM_TYPE_KEY is null THEN NULL ELSE rat.ADM_TYPE END) as AdmitType
				,COALESCE(SU.Client_LOS,0) as Days
				,convert(varchar(2), CASE WHEN rds.DIS_STAT is null then '01' else rds.dis_stat END) as DischargeStatus 
				,case when SU.ICD_PROC_01_KEY=0 or SU.ICD_PROC_01_KEY is null then NULL else LEFT(IP1.ICD_PROC,7) END as ICDProc1
				,case when SU.ICD_PROC_02_KEY=0 or SU.ICD_PROC_02_KEY is null then NULL else LEFT(IP2.ICD_PROC,7) END as ICDProc2
				,case when SU.ICD_PROC_03_KEY=0 or SU.ICD_PROC_03_KEY is null then NULL else LEFT(IP3.ICD_PROC,7) END as ICDProc3
				,case when SU.ICD_PROC_04_KEY=0 or SU.ICD_PROC_04_KEY is null then NULL else LEFT(IP4.ICD_PROC,7) END as ICDProc4
				,case when SU.ICD_PROC_05_KEY=0 or SU.ICD_PROC_05_KEY is null then NULL else LEFT(IP5.ICD_PROC,7) END as ICDProc5
				,case when SU.ICD_PROC_06_KEY=0 or SU.ICD_PROC_06_KEY is null then NULL else LEFT(IP6.ICD_PROC,7) END as ICDProc6
				,case when SU.ICD_PROC_07_KEY=0 or SU.ICD_PROC_07_KEY is null then NULL else LEFT(IP7.ICD_PROC,7) END as ICDProc7
				,case when SU.ICD_PROC_08_KEY=0 or SU.ICD_PROC_08_KEY is null then NULL else LEFT(IP8.ICD_PROC,7) END as ICDProc8
				,case when SU.ICD_PROC_09_KEY=0 or SU.ICD_PROC_09_KEY is null then NULL else LEFT(IP9.ICD_PROC,7) END as ICDProc9
				,case when SU.ICD_PROC_10_KEY=0 or SU.ICD_PROC_10_KEY is null then NULL else LEFT(IP10.ICD_PROC,7) END as ICDProc10
				,case when SU.ICD_PROC_11_KEY=0 or SU.ICD_PROC_11_KEY is null then NULL else LEFT(IP11.ICD_PROC,7) END as ICDProc11
				,case when SU.ICD_PROC_12_KEY=0 or SU.ICD_PROC_12_KEY is null then NULL else LEFT(IP12.ICD_PROC,7) END as ICDProc12
				,case when SU.ICD_PROC_13_KEY=0 or SU.ICD_PROC_13_KEY is null then NULL else LEFT(IP13.ICD_PROC,7) END as ICDProc13
				,case when SU.ICD_PROC_14_KEY=0 or SU.ICD_PROC_14_KEY is null then NULL else LEFT(IP14.ICD_PROC,7) END as ICDProc14
				,case when SU.ICD_PROC_15_KEY=0 or SU.ICD_PROC_15_KEY is null then NULL else LEFT(IP15.ICD_PROC,7) END as ICDProc15
				,case when SU.ICD_PROC_16_KEY=0 or SU.ICD_PROC_16_KEY is null then NULL else LEFT(IP16.ICD_PROC,7) END as ICDProc16
				,case when SU.ICD_PROC_17_KEY=0 or SU.ICD_PROC_17_KEY is null then NULL else LEFT(IP17.ICD_PROC,7) END as ICDProc17
				,case when SU.ICD_PROC_18_KEY=0 or SU.ICD_PROC_18_KEY is null then NULL else LEFT(IP18.ICD_PROC,7) END as ICDProc18
				,case when SU.ICD_PROC_19_KEY=0 or SU.ICD_PROC_19_KEY is null then NULL else LEFT(IP19.ICD_PROC,7) END as ICDProc19
				,case when SU.ICD_PROC_20_KEY=0 or SU.ICD_PROC_20_KEY is null then NULL else LEFT(IP20.ICD_PROC,7) END as ICDProc20
				,case when SU.ICD_PROC_21_KEY=0 or SU.ICD_PROC_21_KEY is null then NULL else LEFT(IP21.ICD_PROC,7) END as ICDProc21
				,case when SU.ICD_PROC_22_KEY=0 or SU.ICD_PROC_22_KEY is null then NULL else LEFT(IP22.ICD_PROC,7) END as ICDProc22
				,case when SU.ICD_PROC_23_KEY=0 or SU.ICD_PROC_23_KEY is null then NULL else LEFT(IP23.ICD_PROC,7) END as ICDProc23
				,case when SU.ICD_PROC_24_KEY=0 or SU.ICD_PROC_24_KEY is null then NULL else LEFT(IP24.ICD_PROC,7) END as ICDProc24
				,case when SU.ICD_PROC_25_KEY=0 or SU.ICD_PROC_25_KEY is null then NULL else LEFT(IP25.ICD_PROC,7) END as ICDProc25
				,case when SU.ICD_PROC_26_KEY=0 or SU.ICD_PROC_26_KEY is null then NULL else LEFT(IP26.ICD_PROC,7) END as ICDProc26
				,case when SU.ICD_PROC_27_KEY=0 or SU.ICD_PROC_27_KEY is null then NULL else LEFT(IP27.ICD_PROC,7) END as ICDProc27
				,case when SU.ICD_PROC_28_KEY=0 or SU.ICD_PROC_28_KEY is null then NULL else LEFT(IP28.ICD_PROC,7) END as ICDProc28
				,case when SU.ICD_PROC_29_KEY=0 or SU.ICD_PROC_29_KEY is null then NULL else LEFT(IP29.ICD_PROC,7) END as ICDProc29
				,case when SU.ICD_PROC_30_KEY=0 or SU.ICD_PROC_30_KEY is null then NULL else LEFT(IP30.ICD_PROC,7) END as ICDProc30
	INTO		DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP4
	FROM		DBO.SERVICES_UB SU
	INNER JOIN	DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1 K ON SU	.SERVICE_MONTH_START_DATE=K.SERVICE_MONTH_START_DATE AND SU.CLAIM_ID_KEY = K.CLAIM_ID_KEY AND SU.SERVICES_KEY = K.SERVICES_KEY AND SU.MI_POST_DATE = K.MI_POST_DATE
	LEFT JOIN	dbo.RFT_UB_BILL_TYPE rubt on rubt.UB_BILL_TYPE_KEY = su.UBBILL_TYPE_KEY
	LEFT JOIN	dbo.RFT_ADM_SRC ras on ras.ADM_SRC_KEY = su.ADM_SRC_KEY
	LEFT JOIN	dbo.RFT_ADM_TYPE rat on rat.ADM_TYPE_KEY = su.ADM_TYPE_KEY
	LEFT JOIN	dbo.RFT_DIS_STAT rds on rds.DIS_STAT_KEY = su.DIS_STAT_KEY and rds.DIS_STAT_DESC is not null
	LEFT JOIN	DBO.RFT_ICD_PROC IP1 ON SU.ICD_PROC_01_KEY = IP1.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP2 ON SU.ICD_PROC_02_KEY = IP2.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP3 ON SU.ICD_PROC_03_KEY = IP3.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP4 ON SU.ICD_PROC_04_KEY = IP4.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP5 ON SU.ICD_PROC_05_KEY = IP5.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP6 ON SU.ICD_PROC_06_KEY = IP6.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP7 ON SU.ICD_PROC_07_KEY = IP7.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP8 ON SU.ICD_PROC_08_KEY = IP8.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP9 ON SU.ICD_PROC_09_KEY = IP9.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP10 ON SU.ICD_PROC_10_KEY = IP10.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP11 ON SU.ICD_PROC_11_KEY = IP11.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP12 ON SU.ICD_PROC_12_KEY = IP12.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP13 ON SU.ICD_PROC_13_KEY = IP13.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP14 ON SU.ICD_PROC_14_KEY = IP14.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP15 ON SU.ICD_PROC_15_KEY = IP15.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP16 ON SU.ICD_PROC_16_KEY = IP16.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP17 ON SU.ICD_PROC_17_KEY = IP17.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP18 ON SU.ICD_PROC_18_KEY = IP18.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP19 ON SU.ICD_PROC_19_KEY = IP19.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP20 ON SU.ICD_PROC_20_KEY = IP20.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP21 ON SU.ICD_PROC_21_KEY = IP21.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP22 ON SU.ICD_PROC_22_KEY = IP22.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP23 ON SU.ICD_PROC_23_KEY = IP23.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP24 ON SU.ICD_PROC_24_KEY = IP24.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP25 ON SU.ICD_PROC_25_KEY = IP25.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP26 ON SU.ICD_PROC_26_KEY = IP26.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP27 ON SU.ICD_PROC_27_KEY = IP27.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP28 ON SU.ICD_PROC_28_KEY = IP28.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP29 ON SU.ICD_PROC_29_KEY = IP29.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_ICD_PROC IP30 ON SU.ICD_PROC_30_KEY = IP30.ICD_PROC_KEY 
	LEFT JOIN	DBO.RFT_DRG DRG
		ON CASE 
				WHEN @DRGPREF='MS' AND @DRGPRIOR = 'MI' THEN  MI_MS_DRG_KEY 
				WHEN @DRGPREF='TRI' AND @DRGPRIOR = 'MI' THEN MI_TRI_DRG_KEY 
				WHEN @DRGPREF='AP' AND @DRGPRIOR = 'MI' THEN MI_AP_DRG_KEY 
				WHEN @DRGPREF='APR' AND @DRGPRIOR = 'MI' THEN MI_APR_DRG_KEY 
				WHEN @DRGPREF='MS' AND @DRGPRIOR = 'CLIENT' THEN MS_DRG_KEY 
				WHEN @DRGPREF='TRI' AND @DRGPRIOR = 'CLIENT' THEN TRI_DRG_KEY 
				WHEN @DRGPREF='AP' AND @DRGPRIOR = 'CLIENT' THEN AP_DRG_KEY 
				WHEN @DRGPREF='APR' AND @DRGPRIOR = 'CLIENT' THEN APR_DRG_KEY 
				ELSE NULL
		END	= DRG.DRG_KEY
	LEFT JOIN	DBO.RFT_REV_CODE RV ON SU.REV_CODE_KEY = RV.REV_CODE_KEY
	
	SET @PERF_ROW=@@ROWCOUNT;
	SET @PERF_DURATION = DATEDIFF(minute,@PERF_START,GETDATE())
	EXEC dbo.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP4 LOADED', @PERF_ROW, @DURATION_IN_MIN=@PERF_DURATION, @LOG2ID=@LOGID;

	
	--Inserting data for input claims. 
	SET @PERF_START = GETDATE();
	TRUNCATE TABLE [DBO].[WORK_HCG_CLAIMS_INPUT]

	INSERT INTO [DBO].[WORK_HCG_CLAIMS_INPUT] WITH (TABLOCK) 
			(
				SequenceNumber,	ClaimID,	LineNum,	ContractID,	MemberID,	DateOfBirth,	Gender,	FromDate,	ToDate,	AdmitDate,	DischDate
				,PaidDate,	DRG,	DRGVersion,	RevCode,	HCPCS,	ModifierCode1,	ModifierCode2,	SourcePlaceOfService,	PlaceOfService,	SourceSpecialty
				,Specialty,	EncounterFlag,	ProviderID,	ProviderZIP,	ProviderCounty,	MedicareID,	BillType,	AdmitSource,	AdmitType,	Billed,	Allowed
				,Paid,	COB,	Copay,	Coinsurance,	Deductible,	PatientPay,	Days,	Units,	DischargeStatus,	ICDVersion,	AdmitDiag
				,ICDDiag1,	ICDDiag2,	ICDDiag3,	ICDDiag4,	ICDDiag5,	ICDDiag6,	ICDDiag7,	ICDDiag8,	ICDDiag9,	ICDDiag10
				,ICDDiag11,	ICDDiag12,	ICDDiag13,	ICDDiag14,	ICDDiag15,	ICDDiag16,	ICDDiag17,	ICDDiag18,	ICDDiag19,	ICDDiag20
				,ICDDiag21,	ICDDiag22,	ICDDiag23,	ICDDiag24,	ICDDiag25,	ICDDiag26,	ICDDiag27,	ICDDiag28,	ICDDiag29,	ICDDiag30
				,POA1,	POA2,	POA3,	POA4,	POA5,	POA6,	POA7,	POA8,	POA9,	POA10,	POA11,	POA12,	POA13,	POA14,	POA15
				,POA16,	POA17,	POA18,	POA19,	POA20,	POA21,	POA22,	POA23,	POA24,	POA25,	POA26,	POA27,	POA28,	POA29,	POA30
				,ICDProc1,	ICDProc2,	ICDProc3,	ICDProc4,	ICDProc5,	ICDProc6,	ICDProc7,	ICDProc8,	ICDProc9,	ICDProc10
				,ICDProc11,	ICDProc12,	ICDProc13,	ICDProc14,	ICDProc15,	ICDProc16,	ICDProc17,	ICDProc18,	ICDProc19,	ICDProc20
				,ICDProc21,	ICDProc22,	ICDProc23,	ICDProc24,	ICDProc25,	ICDProc26,	ICDProc27,	ICDProc28,	ICDProc29,	ICDProc30
				,RiskPool,	OON,	ClaimLineStatus,	CurrentAllowed,	LOINC,	srcLOB,	LOB,	srcProduct,	Product,	GroupID, Zip, County, MemberStatus
				,UserDefPop1,	UserDefPop2,	UserDefPop3,	UserDefNum1,	UserDefNum2,	UserDefNum3
				,SERVICE_MONTH_START_DATE,	SERVICES_KEY,	CLAIM_ID_KEY,	MI_POST_DATE

			)
	SELECT      S.SequenceNumber, S.ClaimID, S.LineNumber, S.ContractID, S.MemberID, S.DateOfBirth, S.Gender, S.FromDate, S.ToDate, SU.AdmitDate, SU.DischargeDate
				,S.PaidDate, SU.DRG, SU.DRGVersion, SU.RevenueCode, S.HCPCS, S.ModifierCode1, S2.ModifierCode2, S.SourcePlaceOfService, S.PlaceOfService, S.SourceSpecialty
				,S.Specialty, S.EncounterFlag, S.ProviderID, S.ProviderZIP, S.ProviderCounty, S.MedicareID, SU.BillType, SU.AdmitSource, SU.AdmitType, S.Billed, S.Allowed
				,S.Paid, S.COB, S.Copay, S.Coinsurance, S.Deductable, S.PatientPay, COALESCE(SU.[Days],0), S.Units, COALESCE(SU.DischargeStatus,'01'), S.ICDVersion, S2.AdmitDiag
				,S.ICD_DIAG_01, S.ICD_DIAG_02, S.ICD_DIAG_03, S.ICD_DIAG_04, S.ICD_DIAG_05, S.ICD_DIAG_06, S.ICD_DIAG_07, S.ICD_DIAG_08, S.ICD_DIAG_09, S.ICD_DIAG_10
				,S2.ICDDiag11, S2.ICDDiag12, S2.ICDDiag13, S2.ICDDiag14, S2.ICDDiag15, S2.ICDDiag16, S2.ICDDiag17, S2.ICDDiag18, S2.ICDDiag19, S2.ICDDiag20
				,S2.ICDDiag21, S2.ICDDiag22, S2.ICDDiag23, S2.ICDDiag24, S2.ICDDiag25, S2.ICDDiag26, S2.ICDDiag27, S2.ICDDiag28, S2.ICDDiag29, S2.ICDDiag30
				,S2.POA1, S2.POA2, S2.POA3, S2.POA4, S2.POA5, S2.POA6, S2.POA7, S2.POA8, S2.POA9, S2.POA10, S2.POA11, S2.POA12, S2.POA13, S2.POA14, S2.POA15
				,S2.POA16, S2.POA17, S2.POA18, S2.POA19, S2.POA20, S2.POA21, S2.POA22, S2.POA23, S2.POA24, S2.POA25, S2.POA26, S2.POA27, S2.POA28, S2.POA29, S2.POA30
				,SU.ICDProc1, SU.ICDProc2, SU.ICDProc3, SU.ICDProc4, SU.ICDProc5, SU.ICDProc6, SU.ICDProc7, SU.ICDProc8, SU.ICDProc9, SU.ICDProc10
				,SU.ICDProc11, SU.ICDProc12, SU.ICDProc13, SU.ICDProc14, SU.ICDProc15, SU.ICDProc16, SU.ICDProc17, SU.ICDProc18, SU.ICDProc19, SU.ICDProc20
				,SU.ICDProc21, SU.ICDProc22, SU.ICDProc23, SU.ICDProc24, SU.ICDProc25, SU.ICDProc26, SU.ICDProc27, SU.ICDProc28, SU.ICDProc29, SU.ICDProc30
				,S.RiskPool, S.OON, S.CLAIM_LINE_STATUS, S.CurrentAllowed, S2.LOINC, S.srcLOB, S.LOB, S.srcProduct, S.Product, S.GroupID, S.Zip, S.County, S.MemberStatus
				,S.UserDefPop1, S.UserDefPop2, S.UserDefPop3, S.UserDefNum1, S.UserDefNum2, S.UserDefNum3
				,S.SERVICE_MONTH_START_DATE, S.SERVICES_KEY, S.CLAIM_ID_KEY, S.MI_POST_DATE
	FROM		DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1 K
	INNER JOIN	DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP2 S ON S.SERVICE_MONTH_START_DATE=K.SERVICE_MONTH_START_DATE AND S.CLAIM_ID_KEY = K.CLAIM_ID_KEY AND S.SERVICES_KEY = K.SERVICES_KEY AND S.MI_POST_DATE = K.MI_POST_DATE
	LEFT JOIN	DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP3 S2 ON S2.SERVICE_MONTH_START_DATE=K.SERVICE_MONTH_START_DATE AND S2.CLAIM_ID_KEY = K.CLAIM_ID_KEY AND S2.SERVICES_KEY = K.SERVICES_KEY AND S2.MI_POST_DATE = K.MI_POST_DATE
	LEFT JOIN	DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP4 SU ON SU	.SERVICE_MONTH_START_DATE=K.SERVICE_MONTH_START_DATE AND SU.CLAIM_ID_KEY = K.CLAIM_ID_KEY AND SU.SERVICES_KEY = K.SERVICES_KEY AND SU.MI_POST_DATE = K.MI_POST_DATE
			
	SET @PERF_ROW=@@ROWCOUNT;
	SET @PERF_DURATION = DATEDIFF(minute,@PERF_START,GETDATE());
	EXEC dbo.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, 'DBO.WORK_HCG_CLAIMS_INPUT LOADED', @PERF_ROW, @DURATION_IN_MIN=@PERF_DURATION, @LOG2ID=@LOGID;

	EXEC DBO.SP_MI_DROPTABLE 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP1'
	EXEC DBO.SP_MI_DROPTABLE 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP2'
	EXEC DBO.SP_MI_DROPTABLE 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP3'
	EXEC DBO.SP_MI_DROPTABLE 'DBO.INPUT_ENR_HCG2019_GRVU_GA_WC_7_0_TEMP4'


	EXEC dbo.SP_MI_UTIL_LOG_EVENT @@PROCID, @DB_ID, @LOG2ID=@LOGID,@END_FLAG=1;		

END




--$LastChangedDate: 2018-05-23 12:46:20 -0700 (Wed, 23 May 2018) $

--$LastChangedRevision: 41904 $

--$Author: schulb $

--$HeadURL: https://topsvcs.medinsight.milliman.com/svn/MedInsight/branches/Database/MI_12/MI/Schema%20Objects/Schemas/dbo/Programmability/Stored%20Procedures/MI_8021_MI_HCG_INPUT_TABLES_MED.sql $


GO


