USE [MI_CBC2017]
GO

/****** Object:  View [CST].[SERVICES_KEYS_HRT]    Script Date: 11/1/2018 3:23:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [CST].[SERVICES_KEYS_HRT]
/* SVN Version #    */
	AS SELECT
	   a.CLAIM_ID_KEY
      ,a.SERVICES_KEY
	  ,a.FROM_DATE
      ,c.CLAIM_ID
	  ,a.MEMBER_KEY
	  ,a.MI_PERSON_KEY
      ,b._CLAIM_UDF_01_ as SequenceNumber 
	  ,Ud1._MI_USER_DIM_01_ as LOB
	  ,ud3._MI_USER_DIM_03_  as HCGIndicator   
	  ,ud5._MI_USER_DIM_05_  as PartialYearGroup
      
  FROM [dbo].[SERVICES] a LEFT JOIN  SERVICES_UDF b
  ON a.SERVICES_KEY = B.SERVIcES_KEY
     and a.CLAIM_ID_KEY = B.CLAIM_ID_KEY
 LEFT JOIN RFT_CLAIM_ID c 
 ON a.CLAIM_ID_KEY = c.CLAIM_ID_KEY
 and a.MEMBER_KEY = c.MEMBER_KEY
LEFT JOIN MI.RFT_MI_USER_DIM_01_  UD1  ON a._MI_USER_DIM_01_KEY =UD1._MI_USER_DIM_01_KEY
LEFT JOIN MI.RFT_MI_USER_DIM_02_  UD2  ON a._MI_USER_DIM_02_KEY =UD2._MI_USER_DIM_02_KEY
LEFT JOIN MI.RFT_MI_USER_DIM_03_  UD3  ON a._MI_USER_DIM_03_KEY =UD3._MI_USER_DIM_03_KEY
LEFT JOIN MI.RFT_MI_USER_DIM_04_  UD4  ON a._MI_USER_DIM_04_KEY =UD4._MI_USER_DIM_04_KEY
LEFT JOIN MI.RFT_MI_USER_DIM_05_  UD5  ON a._MI_USER_DIM_05_KEY =UD5._MI_USER_DIM_05_KEY
LEFT JOIN MI.RFT_MI_USER_DIM_06_  UD6  ON a._MI_USER_DIM_06_KEY =UD6._MI_USER_DIM_06_KEY
LEFT JOIN MI.RFT_MI_USER_DIM_07_  UD7  ON a._MI_USER_DIM_07_KEY =UD7._MI_USER_DIM_07_KEY
LEFT JOIN MI.RFT_MI_USER_DIM_08_  UD8  ON a._MI_USER_DIM_08_KEY =UD8._MI_USER_DIM_08_KEY


--$LastChangedDate: 2017-07-11 14:37:58 -0700 (Tue, 11 Jul 2017) $
--$LastChangedRevision: 32330 $
--$Author: WrightL $
--$HeadURL: https://topsvcs.medinsight.milliman.com/svn/MedInsight/branches/Database/MI_11/HRT/Core/Schemas/cst/Views/CST.SERVICES_KEYS_HRT.sql $	



GO


