USE [MI_CHSD2016]
GO

/****** Object:  StoredProcedure [CST].[CONSOLIDATE_04_EBMS]    Script Date: 3/7/2018 8:03:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [CST].[CONSOLIDATE_04_EBMS] 
	@TRUNCATE VARCHAR(1),
	@INDEX VARCHAR(1)
AS

--------------------------------------------------------------------
-- PREPARE SOURCE FILES FOR TRANSFORMATION TO CONSOLIDATED SYSTEM --
-------------------------------------------------------------------

SET NOCOUNT ON

DECLARE @DB_NAME VARCHAR(50)
DECLARE @CID VARCHAR(2)
DECLARE @SQL VARCHAR(8000) = ''
DECLARE @TABLE_NAME VARCHAR(50)


IF @TRUNCATE = 'Y' BEGIN
	TRUNCATE TABLE EBM.EBM_DETAIL
END

exec SP_MI_TOGGLE_IDX 'EBM.EBM_DETAIL','OFF'

raiserror ('Databases identified for consolidation', 10,1) with nowait

-- OPEN COLUMN CURSOR AND LOOP --
DECLARE db_cursor CURSOR FOR  
SELECT DBS,CID
FROM ##TEMP_DBS 
OPEN db_cursor   
FETCH NEXT FROM db_cursor INTO @DB_NAME,@CID 

WHILE @@FETCH_STATUS = 0 BEGIN  

	SET @SQL = '
	exec sp_mi_droptable ''##EBM_DETAIL''
	SELECT
		'''+@CID + '-'' + M.MEMBER_ID AS MEMBER_ID,
		MEM_START_DATE,
		MEM_END_DATE,
		E.PAYER,
		E.CI_POP_ID,
		E.CI_MEASURE_ID,
		E.ENDING_MONTH,
		DENOMINATOR,
		EXCLUSION,
		NUMERATOR,
		INVERTED_MEASURE,
		LATEST_MONTH_FLAG
	INTO ##EBM_DETAIL
	FROM ' + @DB_NAME + '.EBM.EBM_DETAIL E
			LEFT JOIN ' + @DB_NAME + '.DBO.MEMBER M ON E.MEMBER_KEY = M.MEMBER_KEY '

	EXECUTE(@SQL)

	SET @SQL = 'EBM_DETAIL read from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait

	SET @SQL = '
	INSERT INTO EBM.EBM_DETAIL
	SELECT DISTINCT
		COALESCE(MEMBER_KEY,0) AS MEMBER_KEY,
		E.PAYER,
		E.CI_POP_ID,
		E.CI_MEASURE_ID,
		E.ENDING_MONTH,
		DENOMINATOR,
		EXCLUSION,
		NUMERATOR,
		INVERTED_MEASURE,
		LATEST_MONTH_FLAG
	FROM ##EBM_DETAIL E
		LEFT JOIN MEMBER M ON E.MEMBER_ID = M.MEMBER_ID 
			AND E.MEM_START_DATE = M.MEM_START_DATE
			AND E.MEM_END_DATE = M.MEM_END_DATE --AND ENDING_MONTH BETWEEN MEM_START_DATE AND MEM_END_DATE '

	EXECUTE(@SQL)

	--exec sp_mi_droptable '##EBM_DETAIL'
	SET @SQL = 'Created EBM_DETAIL from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait


	FETCH NEXT FROM db_cursor INTO @DB_NAME,@CID
	
END 

CLOSE db_cursor   
DEALLOCATE db_cursor 

IF @INDEX = 'Y' BEGIN
	exec SP_MI_TOGGLE_IDX 'EBM.EBM_DETAIL','ON'
END


GO


