USE [MI_CBC2017]
GO

/****** Object:  View [CST].[VW_RISK_MARA]    Script Date: 11/1/2018 3:27:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [CST].[VW_RISK_MARA]
/* SVN Version #    */
AS
SELECT 	 
	  '' AS [*=== MARA RISK ===*]
	  ,MARA.MODELNAME 
      ,MARA.[Total]
      ,MARA.[Rx]
      ,MARA.[Medical]
      ,MARA.[IP]
      ,MARA.[OP]
      ,MARA.[Physician]
      ,MARA.[MaxIncurredDate]
      ,MARA.[ER] 
      ,MARA.[Oth]
,MARA.[MI_PERSON_KEY]
,M.[MEMBER_ID]
,M.[MEMBER_ID_ENCRYPTED]

FROM [DBO].[MEMBER_MARA_RESULTS_RISK]  MARA
INNER JOIN dbo.MEMBER M ON MARA.MI_PERSON_KEY = M.MI_PERSON_KEY
INNER JOIN dbo.MI_YEARMO_LIST Y
ON MARA.MaxIncurredDate = Y.FIRST_DATE_IN_MONTH
--INNER JOIN MI.RFT_PROD_TYPE PT
--ON PT.PROD_TYPE='MEDICAL'
--LEFT JOIN dbo.MEMBER_MONTH_MAXPOST MMAX
--	ON  Y.FIRST_DATE_IN_MONTH = MMAX.MEMBER_MONTH_START_DATE 
--	AND MARA.MEMBER_KEY = MMAX.MEMBER_KEY
--    AND PT.PROD_TYPE_KEY = MMAX.PROD_TYPE_KEY
--LEFT JOIN CST.VW_MEMBMTHS MM
--	ON  Y.FIRST_DATE_IN_MONTH = MM.MEMBER_MONTH_START_DATE 
--	AND MARA.MEMBER_KEY = MM.MEMBER_KEY
--    AND PT.PROD_TYPE_KEY = MM.PROD_TYPE_KEY
 --   AND MARA.MI_POST_DATE = MM.MI_POST_DATE
LEFT JOIN dbo.MI_MARA_MODELS RM ON MARA.MODELNAME = RM.MARA_MODEL_ID
--LEFT JOIN dbo.MI_PARMS PX ON PX.PARM='PRIVATE KEY'
--	LEFT JOIN dbo.MI_PARMS RSIG ON RSIG.PARM = 'RUN SIGNATURE'
--	LEFT JOIN dbo.MI_PARMS MIVER ON MIVER.PARM = 'MI VERSION'



--$LastChangedDate$
--$LastChangedRevision$
--$Author$
--$HeadURL$	




GO


