USE [MI_CBC2017]
GO

/****** Object:  View [CST].[VW_RISK_MARA_CONDITIONS]    Script Date: 11/1/2018 3:28:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [CST].[VW_RISK_MARA_CONDITIONS]
/* SVN Version #    */
/* SVN Version #    */
AS
SELECT 
'' as MARA_MODEL_KEY,
'' AS MARA_RISK_MODEL, 
M.MI_PERSON_KEY,
M.MEMBER_ID,
M.MEMBER_ID_ENCRYPTED,
'' as MARACLASS_KEY,
'' as INSTANCES,
12  as LATEST_MONTH,
A.MODELPERCENT as MODEL_PERCENT,
A.MAXINCURREDDATE,
A.MI_POST_DATE,
'' as PRIMARY_RISK,
A.Category AS MARA_CONDITION_CODE,
'' MARA_CONDITION,
''   AS MARA_CODE_AND_CONDITION,
'' as MARA_MODEL_DESC
,RSIG.Setting AS DB_SIG
,MIVER.Setting AS MI_VERSION

FROM dbo.MEMBER_MARA_RESULTS_CLASS A
--LEFT JOIN dbo.RFT_MARA_CLASS MC ON A.MARACLASS_KEY=MC.MARACLASS_KEY
--LEFT JOIN dbo.MI_MARA_MODELS RM ON A.MARA_MODEL_KEY = RM.MARA_MODEL_KEY
LEFT JOIN dbo.MEMBER M ON A.MI_PERSON_KEY = M.MI_PERSON_KEY
LEFT JOIN dbo.MI_PARMS PX ON PX.PARM='PRIVATE KEY'
LEFT JOIN dbo.MI_PARMS RSIG ON RSIG.PARM = 'RUN SIGNATURE'
LEFT JOIN dbo.MI_PARMS MIVER ON MIVER.PARM = 'MI VERSION'







--$LastChangedDate$
--$LastChangedRevision$
--$Author$
--$HeadURL$	



GO


