USE [MI_CHSD2016]
GO

/****** Object:  StoredProcedure [CST].[CONSOLIDATE_02_MEMBER_MONTH_KEYS]    Script Date: 3/7/2018 8:01:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [CST].[CONSOLIDATE_02_MEMBER_MONTH_KEYS]
	@DB_NAME VARCHAR(50),
	@CID VARCHAR(2)
AS

SET NOCOUNT ON

DECLARE @SQL VARCHAR(4000)
SET @SQL = 'MEMBERSHIP KEYS STARTED from ' + @DB_NAME
raiserror (@SQL, 10,1) with nowait

EXEC('
exec sp_mi_droptable ''##RFT_MI_USER_DIM_01_''
SELECT
	S._MI_USER_DIM_01_KEY AS S_MI_USER_DIM_01_KEY,
	T._MI_USER_DIM_01_KEY AS T_MI_USER_DIM_01_KEY,
	S._MI_USER_DIM_01_ AS S_MI_USER_DIM_01_,
	T._MI_USER_DIM_01_ AS T_MI_USER_DIM_01_
INTO ##RFT_MI_USER_DIM_01_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_01_ S
	INNER JOIN RFT_MI_USER_DIM_01_ T 
		ON S._MI_USER_DIM_01_ = T._MI_USER_DIM_01_ 
		OR (S._MI_USER_DIM_01_KEY = 0 AND T._MI_USER_DIM_01_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_01_(S_MI_USER_DIM_01_KEY)

exec sp_mi_droptable ''##RFT_MI_USER_DIM_02_''
SELECT
	S._MI_USER_DIM_02_KEY AS S_MI_USER_DIM_02_KEY,
	T._MI_USER_DIM_02_KEY AS T_MI_USER_DIM_02_KEY,
	S._MI_USER_DIM_02_ AS S_MI_USER_DIM_02_,
	T._MI_USER_DIM_02_ AS T_MI_USER_DIM_02_
INTO ##RFT_MI_USER_DIM_02_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_02_ S
	LEFT JOIN RFT_MI_USER_DIM_02_ T 
		ON S._MI_USER_DIM_02_ = T._MI_USER_DIM_02_ 
		OR (S._MI_USER_DIM_02_KEY = 0 AND T._MI_USER_DIM_02_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_02_(S_MI_USER_DIM_02_KEY)

exec sp_mi_droptable ''##RFT_MI_USER_DIM_03_''
SELECT
	S._MI_USER_DIM_03_KEY AS S_MI_USER_DIM_03_KEY,
	T._MI_USER_DIM_03_KEY AS T_MI_USER_DIM_03_KEY,
	S._MI_USER_DIM_03_ AS S_MI_USER_DIM_03_,
	T._MI_USER_DIM_03_ AS T_MI_USER_DIM_03_
INTO ##RFT_MI_USER_DIM_03_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_03_ S
	LEFT JOIN RFT_MI_USER_DIM_03_ T 
		ON S._MI_USER_DIM_03_ = T._MI_USER_DIM_03_ 
		OR (S._MI_USER_DIM_03_KEY = 0 AND T._MI_USER_DIM_03_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_03_(S_MI_USER_DIM_03_KEY)

exec sp_mi_droptable ''##RFT_MI_USER_DIM_04_''
SELECT
	S._MI_USER_DIM_04_KEY AS S_MI_USER_DIM_04_KEY,
	T._MI_USER_DIM_04_KEY AS T_MI_USER_DIM_04_KEY,
	S._MI_USER_DIM_04_ AS S_MI_USER_DIM_04_,
	T._MI_USER_DIM_04_ AS T_MI_USER_DIM_04_
INTO ##RFT_MI_USER_DIM_04_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_04_ S
	LEFT JOIN RFT_MI_USER_DIM_04_ T 
		ON S._MI_USER_DIM_04_ = T._MI_USER_DIM_04_ 
		OR (S._MI_USER_DIM_04_KEY = 0 AND T._MI_USER_DIM_04_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_04_(S_MI_USER_DIM_04_KEY)

exec sp_mi_droptable ''##RFT_MI_USER_DIM_05_''
SELECT
	S._MI_USER_DIM_05_KEY AS S_MI_USER_DIM_05_KEY,
	T._MI_USER_DIM_05_KEY AS T_MI_USER_DIM_05_KEY,
	S._MI_USER_DIM_05_ AS S_MI_USER_DIM_05_,
	T._MI_USER_DIM_05_ AS T_MI_USER_DIM_05_
INTO ##RFT_MI_USER_DIM_05_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_05_ S
	LEFT JOIN RFT_MI_USER_DIM_05_ T 
		ON S._MI_USER_DIM_05_ = T._MI_USER_DIM_05_ 
		OR (S._MI_USER_DIM_05_KEY = 0 AND T._MI_USER_DIM_05_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_05_(S_MI_USER_DIM_05_KEY)

exec sp_mi_droptable ''##RFT_MI_USER_DIM_06_''
SELECT
	S._MI_USER_DIM_06_KEY AS S_MI_USER_DIM_06_KEY,
	T._MI_USER_DIM_06_KEY AS T_MI_USER_DIM_06_KEY,
	S._MI_USER_DIM_06_ AS S_MI_USER_DIM_06_,
	T._MI_USER_DIM_06_ AS T_MI_USER_DIM_06_
INTO ##RFT_MI_USER_DIM_06_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_06_ S
	LEFT JOIN RFT_MI_USER_DIM_06_ T 
		ON S._MI_USER_DIM_06_ = T._MI_USER_DIM_06_ 
		OR (S._MI_USER_DIM_06_KEY = 0 AND T._MI_USER_DIM_06_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_06_(S_MI_USER_DIM_06_KEY)

exec sp_mi_droptable ''##RFT_MI_USER_DIM_07_''
SELECT
	S._MI_USER_DIM_07_KEY AS S_MI_USER_DIM_07_KEY,
	T._MI_USER_DIM_07_KEY AS T_MI_USER_DIM_07_KEY,
	S._MI_USER_DIM_07_ AS S_MI_USER_DIM_07_,
	T._MI_USER_DIM_07_ AS T_MI_USER_DIM_07_
INTO ##RFT_MI_USER_DIM_07_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_07_ S
	LEFT JOIN RFT_MI_USER_DIM_07_ T 
		ON S._MI_USER_DIM_07_ = T._MI_USER_DIM_07_ 
		OR (S._MI_USER_DIM_07_KEY = 0 AND T._MI_USER_DIM_07_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_07_(S_MI_USER_DIM_07_KEY)

exec sp_mi_droptable ''##RFT_MI_USER_DIM_08_''
SELECT
	S._MI_USER_DIM_08_KEY AS S_MI_USER_DIM_08_KEY,
	T._MI_USER_DIM_08_KEY AS T_MI_USER_DIM_08_KEY,
	S._MI_USER_DIM_08_ AS S_MI_USER_DIM_08_,
	T._MI_USER_DIM_08_ AS T_MI_USER_DIM_08_
INTO ##RFT_MI_USER_DIM_08_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_08_ S
	LEFT JOIN RFT_MI_USER_DIM_08_ T 
		ON S._MI_USER_DIM_08_ = T._MI_USER_DIM_08_ 
		OR (S._MI_USER_DIM_08_KEY = 0 AND T._MI_USER_DIM_08_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_08_(S_MI_USER_DIM_08_KEY)

exec sp_mi_droptable ''##RFT_MI_USER_DIM_09_''
SELECT
	S._MI_USER_DIM_09_KEY AS S_MI_USER_DIM_09_KEY,
	T._MI_USER_DIM_09_KEY AS T_MI_USER_DIM_09_KEY,
	S._MI_USER_DIM_09_ AS S_MI_USER_DIM_09_,
	T._MI_USER_DIM_09_ AS T_MI_USER_DIM_09_
INTO ##RFT_MI_USER_DIM_09_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_09_ S
	LEFT JOIN RFT_MI_USER_DIM_09_ T 
		ON S._MI_USER_DIM_09_ = T._MI_USER_DIM_09_ 
		OR (S._MI_USER_DIM_09_KEY = 0 AND T._MI_USER_DIM_09_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_09_(S_MI_USER_DIM_09_KEY)

exec sp_mi_droptable ''##RFT_MI_USER_DIM_10_''
SELECT
	S._MI_USER_DIM_10_KEY AS S_MI_USER_DIM_10_KEY,
	T._MI_USER_DIM_10_KEY AS T_MI_USER_DIM_10_KEY,
	S._MI_USER_DIM_10_ AS S_MI_USER_DIM_10_,
	T._MI_USER_DIM_10_ AS T_MI_USER_DIM_10_
INTO ##RFT_MI_USER_DIM_10_
FROM ' + @DB_NAME + '.dbo.RFT_MI_USER_DIM_10_ S
	LEFT JOIN RFT_MI_USER_DIM_10_ T 
		ON S._MI_USER_DIM_10_ = T._MI_USER_DIM_10_ 
		OR (S._MI_USER_DIM_10_KEY = 0 AND T._MI_USER_DIM_10_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MI_USER_DIM_10_(S_MI_USER_DIM_10_KEY)

exec sp_mi_droptable ''##RFT_DATA_SOURCE''
SELECT
	S.DATA_SOURCE_KEY AS S_DATA_SOURCE_KEY,
	T.DATA_SOURCE_KEY AS T_DATA_SOURCE_KEY,
	S.DATA_SOURCE AS S_DATA_SOURCE,
	T.DATA_SOURCE AS T_DATA_SOURCE
INTO ##RFT_DATA_SOURCE
FROM ' + @DB_NAME + '.dbo.RFT_DATA_SOURCE S
	LEFT JOIN RFT_DATA_SOURCE T 
		ON S.DATA_SOURCE = T.DATA_SOURCE 
		OR (S.DATA_SOURCE_KEY = 0 AND T.DATA_SOURCE_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_DATA_SOURCE(S_DATA_SOURCE_KEY)

exec sp_mi_droptable ''##RFT_PAYER_TYPE''
SELECT
	S.PAYER_TYPE_KEY AS S_PAYER_TYPE_KEY,
	T.PAYER_TYPE_KEY AS T_PAYER_TYPE_KEY,
	S.PAYER_TYPE AS S_PAYER_TYPE,
	T.PAYER_TYPE AS T_PAYER_TYPE
INTO ##RFT_PAYER_TYPE
FROM ' + @DB_NAME + '.dbo.RFT_PAYER_TYPE S
	LEFT JOIN RFT_PAYER_TYPE T 
		ON S.PAYER_TYPE = T.PAYER_TYPE 
		OR (S.PAYER_TYPE_KEY = 0 AND T.PAYER_TYPE_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_PAYER_TYPE(S_PAYER_TYPE_KEY)

exec sp_mi_droptable ''##RFT_MEM_STAT''
SELECT
	S.MEM_STAT_KEY AS S_MEM_STAT_KEY,
	T.MEM_STAT_KEY AS T_MEM_STAT_KEY,
	S.MEM_STAT AS S_MEM_STAT,
	T.MEM_STAT AS T_MEM_STAT
INTO ##RFT_MEM_STAT
FROM ' + @DB_NAME + '.dbo.RFT_MEM_STAT S
	LEFT JOIN RFT_MEM_STAT T 
		ON S.MEM_STAT = T.MEM_STAT 
		OR (S.MEM_STAT_KEY = 0 AND T.MEM_STAT_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MEM_STAT(S_MEM_STAT_KEY)

exec sp_mi_droptable ''##BENEFIT''
SELECT
	S.BEN_PKG_KEY AS S_BEN_PKG_KEY,
	T.BEN_PKG_KEY AS T_BEN_PKG_KEY,
	S.BEN_PKG_ID AS S_BEN_PKG_ID,
	T.BEN_PKG_ID AS T_BEN_PKG_ID
INTO ##BENEFIT
FROM ' + @DB_NAME + '.dbo.BENEFIT S
	LEFT JOIN BENEFIT T 
		ON S.BEN_PKG_ID = T.BEN_PKG_ID
		AND S.BEN_CAL_YEAR = T.BEN_CAL_YEAR
		AND S.BEN_LOB = T.BEN_LOB
		OR (S.BEN_PKG_KEY = 0 AND T.BEN_PKG_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##BENEFIT(S_BEN_PKG_KEY)

exec sp_mi_droptable ''##RFT_CONTRACT''
SELECT
	S.CONTRACT_KEY AS S_CONTRACT_KEY,
	T.CONTRACT_KEY AS T_CONTRACT_KEY,
	S.CONTRACT AS S_CONTRACT,
	T.CONTRACT AS T_CONTRACT
INTO ##RFT_CONTRACT
FROM ' + @DB_NAME + '.dbo.RFT_CONTRACT S
	LEFT JOIN RFT_CONTRACT T 
		ON S.CONTRACT = T.CONTRACT 
		OR (S.CONTRACT_KEY = 0 AND T.CONTRACT_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_CONTRACT(S_CONTRACT_KEY)

exec sp_mi_droptable ''##RFT_TIER''
SELECT
	S.TIER_KEY AS S_TIER_KEY,
	T.TIER_KEY AS T_TIER_KEY,
	S.TIER AS S_TIER,
	T.TIER AS T_TIER
INTO ##RFT_TIER
FROM ' + @DB_NAME + '.dbo.RFT_TIER S
	LEFT JOIN RFT_TIER T 
		ON S.TIER = T.TIER 
		OR (S.TIER_KEY = 0 AND T.TIER_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_TIER(S_TIER_KEY)

exec sp_mi_droptable ''##RFT_MED_HOME_ID''
SELECT
	S.MED_HOME_ID_KEY AS S_MED_HOME_ID_KEY,
	T.MED_HOME_ID_KEY AS T_MED_HOME_ID_KEY,
	S.MED_HOME_ID AS S_MED_HOME_ID,
	T.MED_HOME_ID AS T_MED_HOME_ID
INTO ##RFT_MED_HOME_ID
FROM ' + @DB_NAME + '.dbo.RFT_MED_HOME_ID S
	LEFT JOIN RFT_MED_HOME_ID T 
		ON S.MED_HOME_ID = T.MED_HOME_ID 
		OR (S.MED_HOME_ID_KEY = 0 AND T.MED_HOME_ID_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_MED_HOME_ID(S_MED_HOME_ID_KEY)

exec sp_mi_droptable ''##RFT_ACO_ID''
SELECT
	S.ACO_ID_KEY AS S_ACO_ID_KEY,
	T.ACO_ID_KEY AS T_ACO_ID_KEY,
	S.ACO_ID AS S_ACO_ID,
	T.ACO_ID AS T_ACO_ID
INTO ##RFT_ACO_ID
FROM ' + @DB_NAME + '.dbo.RFT_ACO_ID S
	LEFT JOIN RFT_ACO_ID T 
		ON S.ACO_ID = T.ACO_ID 
		OR (S.ACO_ID_KEY = 0 AND T.ACO_ID_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_ACO_ID(S_ACO_ID_KEY)

exec sp_mi_droptable ''##RFT_RELATION''
SELECT
	S.RELATION_KEY AS S_RELATION_KEY,
	T.RELATION_KEY AS T_RELATION_KEY,
	S.RELATION AS S_RELATION,
	T.RELATION AS T_RELATION
INTO ##RFT_RELATION
FROM ' + @DB_NAME + '.dbo.RFT_RELATION S
	LEFT JOIN RFT_RELATION T 
		ON S.RELATION = T.RELATION 
		OR (S.RELATION_KEY = 0 AND T.RELATION_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_RELATION(S_RELATION_KEY)

exec sp_mi_droptable ''##RFT_TERM_RSN''
SELECT
	S.TERM_RSN_KEY AS S_TERM_RSN_KEY,
	T.TERM_RSN_KEY AS T_TERM_RSN_KEY,
	S.TERM_RSN AS S_TERM_RSN,
	T.TERM_RSN AS T_TERM_RSN
INTO ##RFT_TERM_RSN
FROM ' + @DB_NAME + '.dbo.RFT_TERM_RSN S
	LEFT JOIN RFT_TERM_RSN T 
		ON S.TERM_RSN = T.TERM_RSN 
		OR (S.TERM_RSN_KEY = 0 AND T.TERM_RSN_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_TERM_RSN(S_TERM_RSN_KEY)

exec sp_mi_droptable ''##RFT_PROD_TYPE''
SELECT
	S.PROD_TYPE_KEY AS S_PROD_TYPE_KEY,
	T.PROD_TYPE_KEY AS T_PROD_TYPE_KEY,
	S.PROD_TYPE AS S_PROD_TYPE,
	T.PROD_TYPE AS T_PROD_TYPE
INTO ##RFT_PROD_TYPE
FROM ' + @DB_NAME + '.dbo.RFT_PROD_TYPE S
	LEFT JOIN RFT_PROD_TYPE T 
		ON S.PROD_TYPE = T.PROD_TYPE 
		OR (S.PROD_TYPE_KEY = 0 AND T.PROD_TYPE_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_PROD_TYPE(S_PROD_TYPE_KEY)

exec sp_mi_droptable ''##EMP_GROUP''
SELECT
	S.GRP_KEY AS S_GRP_KEY,
	T.GRP_KEY AS T_GRP_KEY,
	S.GRP_ID AS S_GRP_ID,
	T.GRP_ID AS T_GRP_ID
INTO ##EMP_GROUP
FROM ' + @DB_NAME + '.dbo.EMP_GROUP S
	LEFT JOIN EMP_GROUP T 
		ON S.GRP_ID = T.GRP_ID 
CREATE UNIQUE CLUSTERED INDEX XPK ON ##EMP_GROUP(S_GRP_KEY)
WITH (IGNORE_DUP_KEY = ON)
INSERT INTO ##EMP_GROUP SELECT 0,0,NULL,NULL


exec sp_mi_droptable ''##PROVIDER''
SELECT 
	S.PROV_KEY AS S_PROV_KEY,
	T.PROV_KEY AS T_PROV_KEY,
	'''+@CID + '-'' + S.PROV_ID AS S_PROV_ID,
	T.PROV_ID AS T_PROV_ID
INTO ##PROVIDER
FROM ' + @DB_NAME + '.dbo.PROVIDER S
	LEFT JOIN PROVIDER T 
		ON '''+@CID + '-'' + S.PROV_ID = T.PROV_ID 
--		OR (S.PROV_KEY = 0 AND T.PROV_KEY = 0)
CREATE UNIQUE CLUSTERED INDEX XPK ON ##PROVIDER(S_PROV_KEY)
WITH (IGNORE_DUP_KEY = ON)
INSERT INTO ##PROVIDER SELECT 0,0,NULL,NULL

exec sp_mi_droptable ''#TEMP_MEMBER_S''
SELECT
	MEMBER_KEY,
	'''+@CID + '-'' + COALESCE(MEMBER_ID,'''') AS MEMBER_ID,
	MEM_START_DATE,
	MEM_END_DATE
INTO #TEMP_MEMBER_S
FROM ' + @DB_NAME + '.dbo.MEMBER

exec sp_mi_droptable ''#TEMP_MEMBER_T''
SELECT
	MEMBER_KEY,
	MEMBER_ID,
	MEM_START_DATE,
	MEM_END_DATE
INTO #TEMP_MEMBER_T
FROM MEMBER

CREATE UNIQUE CLUSTERED INDEX XPK ON #TEMP_MEMBER_S(MEMBER_ID,MEM_START_DATE,MEM_END_DATE)
CREATE UNIQUE CLUSTERED INDEX XPK ON #TEMP_MEMBER_T(MEMBER_ID,MEM_START_DATE,MEM_END_DATE)

exec sp_mi_droptable ''##MEMBER''
SELECT 
	S.MEMBER_KEY AS S_MEMBER_KEY,
	COALESCE(T.MEMBER_KEY,0) AS T_MEMBER_KEY,
	S.MEMBER_ID AS S_MEMBER_ID,
	T.MEMBER_ID AS T_MEMBER_ID
INTO ##MEMBER
FROM #TEMP_MEMBER_S S
	LEFT JOIN #TEMP_MEMBER_T T 
		ON S.MEMBER_ID = T.MEMBER_ID AND S.MEM_START_DATE = T.MEM_START_DATE
			AND S.MEM_END_DATE = T.MEM_END_DATE

CREATE UNIQUE CLUSTERED INDEX XPK ON ##MEMBER(S_MEMBER_KEY)
WITH (IGNORE_DUP_KEY = ON)

INSERT INTO ##MEMBER
SELECT 0 AS S_MEMBER_KEY,0 AS T_MEMBER_KEY,S.MEMBER_ID AS S_MEMBER_ID,S.MEMBER_ID AS T_MEMBER_ID
FROM #TEMP_MEMBER_S S WHERE MEMBER_KEY = 0


exec sp_mi_droptable ''##RFT_PERSON_ID''
SELECT
	S.PERSON_KEY AS S_PERSON_KEY,
	T.PERSON_KEY AS T_PERSON_KEY,
	S.PERSON_ID AS S_PERSON_ID,
	T.PERSON_ID AS T_PERSON_ID
INTO ##RFT_PERSON_ID
FROM ' + @DB_NAME + '.dbo.RFT_PERSON_ID S
	LEFT JOIN RFT_PERSON_ID T 
		ON S.PERSON_ID + ''-' + @CID + ''' = T.PERSON_ID 
CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_PERSON_ID(S_PERSON_KEY)
WITH (IGNORE_DUP_KEY = ON)
INSERT INTO ##RFT_PERSON_ID SELECT 0,0,NULL,NULL

')

SET @SQL = 'MEMBERSHIP KEYS CREATED from ' + @DB_NAME
raiserror (@SQL, 10,1) with nowait


GO

