USE [MI_CHSD2017]
GO

/****** Object:  StoredProcedure [CST].[CONSOLIDATE_03_SERVICES]    Script Date: 5/6/2019 4:02:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO










ALTER PROCEDURE [CST].[CONSOLIDATE_03_SERVICES] 
	@TRUNCATE VARCHAR(1),
	@INDEX VARCHAR(1)
AS

--------------------------------------------------------------------
-- PREPARE SOURCE FILES FOR TRANSFORMATION TO CONSOLIDATED SYSTEM --
-------------------------------------------------------------------

SET NOCOUNT ON

DECLARE @DB_NAME VARCHAR(50)
DECLARE @CID VARCHAR(2)
DECLARE @SQL VARCHAR(8000) = ''
DECLARE @TABLE_NAME VARCHAR(50)

IF @TRUNCATE = 'Y' BEGIN
	TRUNCATE TABLE RFT_CLAIM_ID
	TRUNCATE TABLE SERVICES_UDF
	TRUNCATE TABLE SERVICES_RX
	TRUNCATE TABLE SERVICES_MEG
	TRUNCATE TABLE SERVICES_MEG_FLARE
	TRUNCATE TABLE SERVICES_UB
	TRUNCATE TABLE SERVICES
	TRUNCATE TABLE SERVICES_2
	TRUNCATE TABLE SERVICES_WASTE
	TRUNCATE TABLE SERVICES_HCG
	TRUNCATE TABLE SERVICES_ETG
END

exec SP_MI_TOGGLE_IDX 'SERVICES_UDF','OFF'
exec SP_MI_TOGGLE_IDX 'SERVICES_UB','OFF'
exec SP_MI_TOGGLE_IDX 'SERVICES','OFF'
exec SP_MI_TOGGLE_IDX 'SERVICES_2','OFF'
exec SP_MI_TOGGLE_IDX 'SERVICES_MEG_FLARE','OFF'
exec SP_MI_TOGGLE_IDX 'SERVICES_MEG','OFF'
exec SP_MI_TOGGLE_IDX 'SERVICES_RX','OFF'
exec SP_MI_TOGGLE_IDX 'SERVICES_WASTE','OFF'
exec SP_MI_TOGGLE_IDX 'SERVICES_ETG','OFF'
exec SP_MI_TOGGLE_IDX 'SERVICES_HCG','OFF'


raiserror ('Databases identified for consolidation', 10,1) with nowait

-- OPEN COLUMN CURSOR AND LOOP --
DECLARE db_cursor CURSOR FOR  
SELECT DBS,CID
FROM ##TEMP_DBS 
OPEN db_cursor   
FETCH NEXT FROM db_cursor INTO @DB_NAME,@CID 

WHILE @@FETCH_STATUS = 0 BEGIN  

	EXEC CST.CONSOLIDATE_02_MEMBER_MONTH_KEYS @DB_NAME,@CID
	EXEC CST.CONSOLIDATE_03_SERVICES_KEYS @DB_NAME,@CID

	-- RFT_CLAIM_ID --
	SET @SQL = '
	TRUNCATE TABLE RFT_CLAIM_ID
	exec SP_MI_TOGGLE_IDX ''RFT_CLAIM_ID'',''OFF''

	exec sp_mi_droptable ''#TEMP_CLAIM''
	SELECT
		C.CLAIM_ID_KEY AS S_CLAIM_ID_KEY,
		'''+@CID + '-'' + CLAIM_ID AS CLAIM_ID,
		'''' AS CLAIM_SFX_OR_PARENT,
		T_MEMBER_KEY AS MEMBER_KEY
	INTO #TEMP_CLAIM
	FROM ' + @DB_NAME + '.dbo.RFT_CLAIM_ID C
		LEFT JOIN ##MEMBER M ON C.MEMBER_KEY = M.S_MEMBER_KEY
	CREATE UNIQUE CLUSTERED INDEX XPK ON #TEMP_CLAIM(CLAIM_ID,MEMBER_KEY)

	INSERT INTO RFT_CLAIM_ID(
		CLAIM_ID,
		CLAIM_SFX_OR_PARENT,
		MEMBER_KEY
	)
	SELECT
		CLAIM_ID,
		CLAIM_SFX_OR_PARENT,
		MEMBER_KEY
	FROM #TEMP_CLAIM
	exec SP_MI_TOGGLE_IDX ''RFT_CLAIM_ID'',''ON''

	exec sp_mi_droptable ''##RFT_CLAIM_ID''
	SELECT
		S.S_CLAIM_ID_KEY,
		T.CLAIM_ID_KEY AS T_CLAIM_ID_KEY,
		S.CLAIM_ID,
		S.CLAIM_SFX_OR_PARENT,
		S.MEMBER_KEY
	INTO ##RFT_CLAIM_ID
	FROM #TEMP_CLAIM S
		INNER JOIN RFT_CLAIM_ID T
			ON S.CLAIM_ID = T.CLAIM_ID
			AND S.MEMBER_KEY = T.MEMBER_KEY
	CREATE UNIQUE CLUSTERED INDEX XPK ON ##RFT_CLAIM_ID(S_CLAIM_ID_KEY)  '
	EXECUTE(@SQL)

	SET @SQL = 'Created RFT_CLAIM_ID from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait


	DECLARE @MIN_DATE varchar(10)

	SET @SQL = '
	exec sp_mi_droptable ''##TEMP_DATES''
	SELECT
		DISTINCT CAST(SERVICE_MONTH_START_DATE AS VARCHAR(10)) AS MIN_DATE
	INTO ##TEMP_DATES
	FROM '+@DB_NAME+'.DBO.SERVICES 
	ORDER BY CAST(SERVICE_MONTH_START_DATE AS VARCHAR(10)) '
	EXECUTE(@SQL)
	
	DECLARE date_cursor CURSOR FOR  
	SELECT
		MIN_DATE
	FROM ##TEMP_DATES 
	ORDER BY MIN_DATE
	OPEN date_cursor   
	FETCH NEXT FROM date_cursor INTO @MIN_DATE 

	WHILE @@FETCH_STATUS = 0 BEGIN

		SET @SQL = '
		INSERT INTO SERVICES(SERVICE_MONTH_START_DATE,MEMBER_KEY,FROM_DATE,CLAIM_ID_KEY,SERVICES_KEY,MI_POST_DATE,
			MI_PERSON_KEY,SV_LINE,FORM_TYPE,SV_STAT,TO_DATE,SUBSCRIBER_KEY,	RELATION_KEY,AGE_ON_DOS,GENDER,GRP_KEY,
			_MI_USER_DIM_01_KEY,_MI_USER_DIM_02_KEY,_MI_USER_DIM_03_KEY,_MI_USER_DIM_04_KEY,_MI_USER_DIM_05_KEY,
			_MI_USER_DIM_06_KEY,_MI_USER_DIM_07_KEY,_MI_USER_DIM_08_KEY,_MI_USER_DIM_09_KEY,_MI_USER_DIM_10_KEY,
			PAID_MONTH_START_DATE,PAID_DATE, CHK_KEY,ICD_DIAG_01_KEY,ICD_DIAG_02_KEY,ICD_DIAG_03_KEY,ICD_DIAG_04_KEY,ICD_DIAG_05_KEY,ICD_DIAG_06_KEY,
			ICD_DIAG_07_KEY,ICD_DIAG_08_KEY,ATT_PROV_KEY,ATT_PROV_SPEC_KEY,	ATT_PROV_IPA_KEY,BILL_PROV_KEY,PROV_NET_FLAG, 
			REF_PROV_KEY,CONTRACT_KEY, BEN_PKG_KEY,POS_KEY,TOS_KEY,PROD_TYPE_KEY,PROC_CODE_KEY,PROC_MOD1_KEY,SV_UNITS,AMT_BILLED,AMT_ALLOWED,AMT_ALLOWED_STAT,AMT_PAID,AMT_DEDUCT,AMT_COINS,
			AMT_COPAY,AMT_COB,AMT_BILLED_DISC,AMT_ALLOWED_DISC, CS_CLAIM_ID_KEY,MR_LINE_CASE_KEY,MI_CASES,MI_UTILS,PBP_LINE_KEY,HCG_VERSION_KEY,
			MEDICARE_COVERED,PPACA_PREVENT,EXCLUSION_CODE,MR_ADMITS_CASES_RAW,MR_UNITS_DAYS_RAW,MR_PROCS_RAW,PBP_ADMITS_CASES_RAW,MK.MR_LINE_KEY,
			CASES_COMP_FACTOR,UTILS_COMP_FACTOR,PAID_COMP_FACTOR,BILLED_COMP_FACTOR,
			CASES_COMP_low,CASES_COMP_high,UTILS_COMP_low,UTILS_COMP_high,BILLED_COMP_low,BILLED_COMP_high,PAID_COMP_low,PAID_COMP_high,
			AGE,CLAIM_IN_NETWORK,ROWCONTROL_KEY,PROV_DOMESTIC,MEMBER_MONTH_KEY,
			MEMBER_MONTH_DEFAULTED,MEMBER_MONTH_DEFAULTED_PRODUCT_LEVEL,ICD_DIAG_09_KEY,ICD_DIAG_10_KEY,FACILITY_CLAIM_ID_KEY
			,[HCG_AMOUNT_BILLED],[HCG_AMOUNT_ALLOWED],[HCG_AMOUNT_PAID],[HCG_AMOUNT_PATIENTPAY]	)
		SELECT 
			S.SERVICE_MONTH_START_DATE,M.T_MEMBER_KEY,S.FROM_DATE,CI.T_CLAIM_ID_KEY AS CLAIM_ID_KEY,
			K.T_SERVICES_KEY AS SERVICES_KEY,S.MI_POST_DATE,COALESCE(T_PERSON_KEY,0) AS PERSON_KEY,
			SV_LINE,FORM_TYPE,SV_STAT,TO_DATE,COALESCE(SUB.T_MEMBER_KEY,0) AS SUBSCRIBER_KEY,
			T_RELATION_KEY AS RELATION,AGE_ON_DOS,COALESCE(S.GENDER,''U''),COALESCE(T_GRP_KEY,0),
			COALESCE(T_MI_USER_DIM_01_KEY,0) AS _MI_USER_DIM_01_KEY,COALESCE(T_MI_USER_DIM_02_KEY,0) AS _MI_USER_DIM_02_KEY,
			COALESCE(T_MI_USER_DIM_03_KEY,0) AS _MI_USER_DIM_03_KEY,COALESCE(T_MI_USER_DIM_04_KEY,0) AS _MI_USER_DIM_04_KEY,
			COALESCE(T_MI_USER_DIM_05_KEY,0) AS _MI_USER_DIM_05_KEY,COALESCE(T_MI_USER_DIM_06_KEY,0) AS _MI_USER_DIM_06_KEY,
			COALESCE(T_MI_USER_DIM_07_KEY,0) AS _MI_USER_DIM_07_KEY,COALESCE(T_MI_USER_DIM_08_KEY,0) AS _MI_USER_DIM_08_KEY,
			COALESCE(T_MI_USER_DIM_09_KEY,0) AS _MI_USER_DIM_09_KEY,COALESCE(T_MI_USER_DIM_10_KEY,0) AS _MI_USER_DIM_10_KEY,
			PAID_MONTH_START_DATE,PAID_DATE, 0 AS CHK_KEY,COALESCE(I01.T_ICD_DIAG_KEY,0) AS ICD_DIAG_01_KEY,COALESCE(I02.T_ICD_DIAG_KEY,0) AS ICD_DIAG_02_KEY,
			COALESCE(I03.T_ICD_DIAG_KEY,0) AS ICD_DIAG_03_KEY,COALESCE(I04.T_ICD_DIAG_KEY,0) AS ICD_DIAG_04_KEY,
			COALESCE(I05.T_ICD_DIAG_KEY,0) AS ICD_DIAG_05_KEY,COALESCE(I06.T_ICD_DIAG_KEY,0) AS ICD_DIAG_06_KEY,
			COALESCE(I07.T_ICD_DIAG_KEY,0) AS ICD_DIAG_07_KEY,COALESCE(I08.T_ICD_DIAG_KEY,0) AS ICD_DIAG_08_KEY,
			COALESCE(AP.T_PROV_KEY,0) AS ATT_PROV_KEY,0 as ATT_PROV_SPEC_KEY,0 AS ATT_PROV_IPA_KEY,
			COALESCE(BP.T_PROV_KEY,0) AS BILL_PROV_KEY,COALESCE(S.PROV_NET_FLAG,''U'') AS PROV_NET_FLAG, 0 AS REF_PROV_KEY,0 AS CONTRACT_KEY, 0 AS BEN_PKG_KEY,
			COALESCE(T_POS_KEY,0) AS POS_KEY,COALESCE(T_TOS_KEY,0) AS TOS_KEY,COALESCE(PR.T_PROD_TYPE_KEY,0) AS PROD_TYPE_KEY,
			COALESCE(T_PROC_CODE_KEY,0) AS PROC_CODE_KEY,COALESCE(T_CPT_MOD_KEY,0) AS CPT_MOD_KEY,SV_UNITS,AMT_BILLED,AMT_ALLOWED,AMT_ALLOWED_STAT,AMT_PAID,AMT_DEDUCT,AMT_COINS,AMT_COPAY,AMT_COB,
			AMT_BILLED_DISC,AMT_ALLOWED_DISC,RCC.T_CLAIM_ID_KEY AS CS_CLAIM_ID_KEY,MR.T_MR_LINE_KEY AS MR_LINE_CASE_KEY,MI_CASES,MI_UTILS,
			T_PBP_LINE_KEY AS PBP_LINE_KEY,HCG_VERSION_KEY,S.MEDICARE_COVERED,PPACA_PREVENT,EXCLUSION_CODE,
			MR_ADMITS_CASES_RAW,MR_UNITS_DAYS_RAW,MR_PROCS_RAW,PBP_ADMITS_CASES_RAW,
			MK.T_MR_LINE_KEY AS MR_LINE_KEY,CASES_COMP_FACTOR,UTILS_COMP_FACTOR,PAID_COMP_FACTOR,BILLED_COMP_FACTOR,
			CASES_COMP_low,CASES_COMP_high,UTILS_COMP_low,UTILS_COMP_high,BILLED_COMP_low,BILLED_COMP_high,PAID_COMP_low,PAID_COMP_high,
			S.AGE,CLAIM_IN_NETWORK,S.ROWCONTROL_KEY,S.PROV_DOMESTIC,COALESCE(MMT.T_MEMBER_MONTH_KEY,0),
			MEMBER_MONTH_DEFAULTED,MEMBER_MONTH_DEFAULTED_PRODUCT_LEVEL,COALESCE(I09.T_ICD_DIAG_KEY,0) AS ICD_DIAG_09_KEY,
			COALESCE(I10.T_ICD_DIAG_KEY,0) AS ICD_DIAG_10_KEY,COALESCE(FACCI.T_CLAIM_ID_KEY,0) AS FACILITY_CLAIM_ID_KEY
			,[HCG_AMOUNT_BILLED],[HCG_AMOUNT_ALLOWED],[HCG_AMOUNT_PAID],HCG_AMOUNT_COPAY+HCG_AMOUNT_COINSURANCE+HCG_AMOUNT_DEDUCTIBLE as [HCG_AMOUNT_PATIENTPAY]
		FROM ' + @DB_NAME + '.DBO.SERVICES S 
			LEFT JOIN CST.CONSOLIDATE_SERVICEKEY K ON K.CID = '''+@CID + ''' AND S.SERVICES_KEY = K.S_SERVICES_KEY
			LEFT JOIN ##MEMBER M ON S.MEMBER_KEY = M.S_MEMBER_KEY
			LEFT JOIN ##RFT_PERSON_ID P ON S.MI_PERSON_KEY = P.S_PERSON_KEY
			LEFT JOIN ##MEMBER SUB ON S.SUBSCRIBER_KEY = SUB.S_MEMBER_KEY
			LEFT JOIN ##RFT_CLAIM_ID CI ON S.CLAIM_ID_KEY = CI.S_CLAIM_ID_KEY
			LEFT JOIN ##RFT_CLAIM_ID FACCI ON S.FACILITY_CLAIM_ID_KEY = FACCI.S_CLAIM_ID_KEY
			LEFT JOIN ##RFT_CLAIM_ID RCC ON S.CS_CLAIM_ID_KEY = RCC.S_CLAIM_ID_KEY
			LEFT JOIN ##MEMBER_MONTH MMT ON S.MEMBER_MONTH_KEY = MMT.S_MEMBER_MONTH_KEY
			LEFT JOIN ##RFT_RELATION R ON S.RELATION_KEY = R.S_RELATION_KEY
			LEFT JOIN ##EMP_GROUP G ON S.GRP_KEY = G.S_GRP_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_01_ U01 ON S._MI_USER_DIM_01_KEY = U01.S_MI_USER_DIM_01_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_02_ U02 ON S._MI_USER_DIM_02_KEY = U02.S_MI_USER_DIM_02_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_03_ U03 ON S._MI_USER_DIM_03_KEY = U03.S_MI_USER_DIM_03_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_04_ U04 ON S._MI_USER_DIM_04_KEY = U04.S_MI_USER_DIM_04_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_05_ U05 ON S._MI_USER_DIM_05_KEY = U05.S_MI_USER_DIM_05_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_06_ U06 ON S._MI_USER_DIM_06_KEY = U06.S_MI_USER_DIM_06_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_07_ U07 ON S._MI_USER_DIM_07_KEY = U07.S_MI_USER_DIM_07_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_08_ U08 ON S._MI_USER_DIM_08_KEY = U08.S_MI_USER_DIM_08_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_09_ U09 ON S._MI_USER_DIM_09_KEY = U09.S_MI_USER_DIM_09_KEY
			LEFT JOIN ##RFT_MI_USER_DIM_10_ U10 ON S._MI_USER_DIM_10_KEY = U10.S_MI_USER_DIM_10_KEY
			LEFT JOIN ##RFT_ICD_DIAG I01 ON S.ICD_DIAG_01_KEY = I01.S_ICD_DIAG_KEY
			LEFT JOIN ##RFT_ICD_DIAG I02 ON S.ICD_DIAG_02_KEY = I02.S_ICD_DIAG_KEY
			LEFT JOIN ##RFT_ICD_DIAG I03 ON S.ICD_DIAG_03_KEY = I03.S_ICD_DIAG_KEY
			LEFT JOIN ##RFT_ICD_DIAG I04 ON S.ICD_DIAG_04_KEY = I04.S_ICD_DIAG_KEY
			LEFT JOIN ##RFT_ICD_DIAG I05 ON S.ICD_DIAG_05_KEY = I05.S_ICD_DIAG_KEY
			LEFT JOIN ##RFT_ICD_DIAG I06 ON S.ICD_DIAG_06_KEY = I06.S_ICD_DIAG_KEY
			LEFT JOIN ##RFT_ICD_DIAG I07 ON S.ICD_DIAG_07_KEY = I07.S_ICD_DIAG_KEY
			LEFT JOIN ##RFT_ICD_DIAG I08 ON S.ICD_DIAG_08_KEY = I08.S_ICD_DIAG_KEY
			LEFT JOIN ##RFT_ICD_DIAG I09 ON S.ICD_DIAG_09_KEY = I09.S_ICD_DIAG_KEY
			LEFT JOIN ##RFT_ICD_DIAG I10 ON S.ICD_DIAG_10_KEY = I10.S_ICD_DIAG_KEY
			LEFT JOIN ##PROVIDER AP ON S.ATT_PROV_KEY = AP.S_PROV_KEY 
			LEFT JOIN ##PROVIDER BP ON S.BILL_PROV_KEY = BP.S_PROV_KEY
			LEFT JOIN ##RFT_POS PS ON S.POS_KEY = PS.S_POS_KEY LEFT JOIN ##RFT_TOS TS ON S.TOS_KEY = TS.S_TOS_KEY
			LEFT JOIN ##RFT_PROD_TYPE PR ON S.PROD_TYPE_KEY = PR.S_PROD_TYPE_KEY
			LEFT JOIN ##RFT_PROC_CODE PC ON S.PROC_CODE_KEY = PC.S_PROC_CODE_KEY		
			LEFT JOIN ##RFT_CPT_MOD CM ON S.PROC_MOD1_KEY = CM.S_CPT_MOD_KEY	
			LEFT JOIN ##RFT_MRLINE_TAB MR ON S.MR_LINE_CASE_KEY = MR.S_MR_LINE_KEY	LEFT JOIN ##RFT_MRLINE_TAB MK ON S.MR_LINE_KEY = MK.S_MR_LINE_KEY	
			LEFT JOIN ##RFT_PBPLINE_TAB PB ON S.PBP_LINE_KEY = PB.S_PBP_LINE_KEY WHERE S.SERVICE_MONTH_START_DATE = '''+@MIN_DATE+''' '

	--PRINT @SQL
	EXECUTE(@SQL)

		SET @SQL = '     ' + @MIN_DATE
		raiserror (@SQL, 10,1) with nowait
		SET @SQL = ''
		raiserror (@SQL, 10,1) with nowait	
		
		FETCH NEXT FROM date_cursor INTO @MIN_DATE 
	END 
	CLOSE date_cursor   
	DEALLOCATE date_cursor

	SET @SQL = 'SERVICES read and consolidated from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait

	SET @SQL = '
	INSERT INTO SERVICES_2(
	[SERVICE_MONTH_START_DATE]
      ,[CLAIM_ID_KEY]
      ,[SERVICES_KEY]
      ,[MI_POST_DATE]
      ,[ICD_DIAG_ADMIT_KEY]
      ,[ICD_DIAG_11_KEY],[ICD_DIAG_12_KEY] ,[ICD_DIAG_13_KEY],[ICD_DIAG_14_KEY]
      ,[ICD_DIAG_15_KEY],[ICD_DIAG_16_KEY],[ICD_DIAG_17_KEY],[ICD_DIAG_18_KEY],[ICD_DIAG_19_KEY]
      ,[ICD_DIAG_20_KEY],[ICD_DIAG_21_KEY],[ICD_DIAG_22_KEY],[ICD_DIAG_23_KEY],[ICD_DIAG_24_KEY]
      ,[ICD_DIAG_25_KEY],[ICD_DIAG_26_KEY],[ICD_DIAG_27_KEY],[ICD_DIAG_28_KEY] ,[ICD_DIAG_29_KEY]
      ,[ICD_DIAG_30_KEY],[ICD_DIAG_01_POA],[ICD_DIAG_02_POA],[ICD_DIAG_03_POA] ,[ICD_DIAG_04_POA]
      ,[ICD_DIAG_05_POA] ,[ICD_DIAG_06_POA] ,[ICD_DIAG_07_POA] ,[ICD_DIAG_08_POA] ,[ICD_DIAG_09_POA]
      ,[ICD_DIAG_10_POA]
      ,[PROC_MOD2_KEY]
      ,[AUTH_KEY]
      ,[CL_DATA_SRC_KEY]
      ,[_MI_USER_DIM_01_ASPAID_KEY]
      ,[_MI_USER_DIM_02_ASPAID_KEY]
      ,[_MI_USER_DIM_03_ASPAID_KEY]
      ,[_MI_USER_DIM_04_ASPAID_KEY]
      ,[_MI_USER_DIM_05_ASPAID_KEY]
      ,[_MI_USER_DIM_06_ASPAID_KEY]
      ,[_MI_USER_DIM_07_ASPAID_KEY]
      ,[_MI_USER_DIM_08_ASPAID_KEY]
      ,[_MI_USER_DIM_09_ASPAID_KEY]
      ,[_MI_USER_DIM_10_ASPAID_KEY]
      ,[RVU_MI_BILLED]
      ,[RVU_MI_ALLOWED]
      ,[RVU_MI_CURRENT_ALLOWED]
      ,[RVU_DEFAULT_BASIS]
      ,[RVU_FINAL_STEP]
      ,[RVU_FINAL]
      ,[RVU_CONVERSION_FACTOR]
      ,[RVU_CF_INCLUDE]
      ,[RVU_ADJUSTED_UNITS]
      ,[RVU_IMPUTE_BASIS]
      ,[MEDICARE_INCLUDE]
      ,[MEDICARE_ADJUDICATED]
      ,[MEDICARE_ALLOWED_BASE_NTNWD]
      ,[MEDICARE_ALLOWED_BASE]
      ,[MEDICARE_OUTLIER]
      ,[MEDICARE_DSH_UCP]
      ,[MEDICARE_CAP_IME]
      ,[MEDICARE_OP_IME]
      ,[MEDICARE_ADJUSTED_UNITS]
      ,[MEDICARE_FEE_SCHEDULE]
      ,[MEDICARE_APC_DRG_HCPCS]
      ,[MEDICARE_STATUS_LOOKUP]
      ,[AMT_PAID_BASIS]
      ,[AMT_ALLOWED_BASIS]
      ,[AMT_BILLED_BASIS])
	SELECT 
	[SERVICE_MONTH_START_DATE]
      ,CI.T_CLAIM_ID_KEY
      ,K.T_SERVICES_KEY
      ,S2.MI_POST_DATE
	  ,COALESCE(ADX.T_ICD_DIAG_KEY,0) AS ICD_DIAG_ADMIT_KEY,COALESCE(DX11.T_ICD_DIAG_KEY,0) AS ICD_DIAG_11_KEY
	  ,COALESCE(DX12.T_ICD_DIAG_KEY,0) AS ICD_DIAG_12_KEY,COALESCE(DX13.T_ICD_DIAG_KEY,0) AS ICD_DIAG_13_KEY
	  ,COALESCE(DX14.T_ICD_DIAG_KEY,0) AS ICD_DIAG_14_KEY,COALESCE(DX15.T_ICD_DIAG_KEY,0) AS ICD_DIAG_15_KEY
	  ,COALESCE(DX16.T_ICD_DIAG_KEY,0) AS ICD_DIAG_16_KEY,COALESCE(DX17.T_ICD_DIAG_KEY,0) AS ICD_DIAG_17_KEY
	  ,COALESCE(DX18.T_ICD_DIAG_KEY,0) AS ICD_DIAG_18_KEY,COALESCE(DX19.T_ICD_DIAG_KEY,0) AS ICD_DIAG_19_KEY
	  ,COALESCE(DX20.T_ICD_DIAG_KEY,0) AS ICD_DIAG_20_KEY
      ,0 as [ICD_DIAG_21_KEY],0 as [ICD_DIAG_22_KEY] ,0 as [ICD_DIAG_23_KEY] ,0 as [ICD_DIAG_24_KEY]
      ,0 as [ICD_DIAG_25_KEY],0 as [ICD_DIAG_26_KEY],0 as [ICD_DIAG_27_KEY],0 as [ICD_DIAG_28_KEY]
      ,0 as [ICD_DIAG_29_KEY],0 as [ICD_DIAG_30_KEY]
      ,[ICD_DIAG_01_POA] ,[ICD_DIAG_02_POA] ,[ICD_DIAG_03_POA] ,[ICD_DIAG_04_POA] ,[ICD_DIAG_05_POA]
      ,[ICD_DIAG_06_POA],[ICD_DIAG_07_POA],[ICD_DIAG_08_POA],[ICD_DIAG_09_POA],[ICD_DIAG_10_POA]     
      ,[PROC_MOD2_KEY]
      ,0 as [AUTH_KEY]
      ,D.T_DATA_SOURCE_KEY AS [CL_DATA_SRC_KEY]
	  ,U01.T_MI_USER_DIM_01_KEY AS _MI_USER_DIM_01_KEY
	  ,U02.T_MI_USER_DIM_02_KEY AS _MI_USER_DIM_02_KEY
	  ,U03.T_MI_USER_DIM_03_KEY AS _MI_USER_DIM_03_KEY
	  ,U04.T_MI_USER_DIM_04_KEY AS _MI_USER_DIM_04_KEY
	  ,U05.T_MI_USER_DIM_05_KEY AS _MI_USER_DIM_05_KEY
	  ,U06.T_MI_USER_DIM_06_KEY AS _MI_USER_DIM_06_KEY
	  ,U07.T_MI_USER_DIM_07_KEY AS _MI_USER_DIM_07_KEY
	  ,U08.T_MI_USER_DIM_08_KEY AS _MI_USER_DIM_08_KEY
	  ,U09.T_MI_USER_DIM_09_KEY AS _MI_USER_DIM_09_KEY
	  ,U10.T_MI_USER_DIM_10_KEY AS _MI_USER_DIM_10_KEY    
      ,[RVU_MI_BILLED]
      ,[RVU_MI_ALLOWED]
      ,[RVU_MI_CURRENT_ALLOWED]
      ,[RVU_DEFAULT_BASIS]
      ,[RVU_FINAL_STEP]
      ,[RVU_FINAL]
      ,[RVU_CONVERSION_FACTOR]
      ,[RVU_CF_INCLUDE]
      ,[RVU_ADJUSTED_UNITS]
      ,[RVU_IMPUTE_BASIS]
      ,[MEDICARE_INCLUDE]
      ,[MEDICARE_ADJUDICATED]
      ,[MEDICARE_ALLOWED_BASE_NTNWD]
      ,[MEDICARE_ALLOWED_BASE]
      ,[MEDICARE_OUTLIER]
      ,[MEDICARE_DSH_UCP]
      ,[MEDICARE_CAP_IME]
      ,[MEDICARE_OP_IME]
      ,[MEDICARE_ADJUSTED_UNITS]
      ,[MEDICARE_FEE_SCHEDULE]
      ,[MEDICARE_APC_DRG_HCPCS]
      ,[MEDICARE_STATUS_LOOKUP]
      ,[AMT_PAID_BASIS]
      ,[AMT_ALLOWED_BASIS]
      ,[AMT_BILLED_BASIS]
	FROM ' + @DB_NAME + '.DBO.SERVICES_2 S2
		LEFT JOIN CST.CONSOLIDATE_SERVICEKEY K ON K.CID = '''+@CID + ''' AND S2.SERVICES_KEY = K.S_SERVICES_KEY
		LEFT JOIN ##RFT_DATA_SOURCE D ON S2.CL_DATA_SRC_KEY = D.S_DATA_SOURCE_KEY
		LEFT JOIN ##RFT_CLAIM_ID CI ON S2.CLAIM_ID_KEY = CI.S_CLAIM_ID_KEY
		LEFT JOIN ##RFT_ICD_DIAG ADX ON S2.ICD_DIAG_ADMIT_KEY = ADX.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX11 ON S2.ICD_DIAG_11_KEY = DX11.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX12 ON S2.ICD_DIAG_12_KEY = DX12.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX13 ON S2.ICD_DIAG_13_KEY = DX13.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX14 ON S2.ICD_DIAG_14_KEY = DX14.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX15 ON S2.ICD_DIAG_15_KEY = DX15.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX16 ON S2.ICD_DIAG_16_KEY = DX16.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX17 ON S2.ICD_DIAG_17_KEY = DX17.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX18 ON S2.ICD_DIAG_18_KEY = DX18.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX19 ON S2.ICD_DIAG_19_KEY = DX19.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_ICD_DIAG DX20 ON S2.ICD_DIAG_20_KEY = DX20.S_ICD_DIAG_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_01_ U01 ON S2._MI_USER_DIM_01_ASPAID_KEY = U01.S_MI_USER_DIM_01_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_02_ U02 ON S2._MI_USER_DIM_02_ASPAID_KEY = U02.S_MI_USER_DIM_02_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_03_ U03 ON S2._MI_USER_DIM_03_ASPAID_KEY = U03.S_MI_USER_DIM_03_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_04_ U04 ON S2._MI_USER_DIM_04_ASPAID_KEY = U04.S_MI_USER_DIM_04_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_05_ U05 ON S2._MI_USER_DIM_05_ASPAID_KEY = U05.S_MI_USER_DIM_05_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_06_ U06 ON S2._MI_USER_DIM_06_ASPAID_KEY = U06.S_MI_USER_DIM_06_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_07_ U07 ON S2._MI_USER_DIM_07_ASPAID_KEY = U07.S_MI_USER_DIM_07_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_08_ U08 ON S2._MI_USER_DIM_08_ASPAID_KEY = U08.S_MI_USER_DIM_08_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_09_ U09 ON S2._MI_USER_DIM_09_ASPAID_KEY = U09.S_MI_USER_DIM_09_KEY
		LEFT JOIN ##RFT_MI_USER_DIM_10_ U10 ON S2._MI_USER_DIM_10_ASPAID_KEY = U10.S_MI_USER_DIM_10_KEY 
		LEFT JOIN ##RFT_CPT_MOD CM ON S2.PROC_MOD2_KEY = CM.S_CPT_MOD_KEY	'
	--PRINT @SQL

	EXECUTE(@SQL)
	
	SET @SQL = 'SERVICES_2 read and consolidated from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait

	SET @SQL = '
	INSERT INTO SERVICES_UDF(
		SERVICE_MONTH_START_DATE,
		CLAIM_ID_KEY,
		SERVICES_KEY,
		MI_POST_DATE,
		_CLAIM_UDF_01_,_CLAIM_UDF_02_,_CLAIM_UDF_03_,_CLAIM_UDF_04_,_CLAIM_UDF_05_,
		_CLAIM_UDF_06_,_CLAIM_UDF_07_,_CLAIM_UDF_08_,_CLAIM_UDF_09_,_CLAIM_UDF_10_,
		_CLAIM_UDF_11_,_CLAIM_UDF_12_,_CLAIM_UDF_13_,_CLAIM_UDF_14_,_CLAIM_UDF_15_,
		_CLAIM_UDF_16_,_CLAIM_UDF_17_,_CLAIM_UDF_18_,_CLAIM_UDF_19_,_CLAIM_UDF_20_,
		_CLAIM_UDF_21_,_CLAIM_UDF_22_,_CLAIM_UDF_23_,_CLAIM_UDF_24_,_CLAIM_UDF_25_,
		_CLAIM_UDF_26_,_CLAIM_UDF_27_,_CLAIM_UDF_28_,_CLAIM_UDF_29_,_CLAIM_UDF_30_,
		_CLAIM_UDF_31_,_CLAIM_UDF_32_,_CLAIM_UDF_33_,_CLAIM_UDF_34_,_CLAIM_UDF_35_,
		_CLAIM_UDF_36_,_CLAIM_UDF_37_,_CLAIM_UDF_38_,_CLAIM_UDF_39_,_CLAIM_UDF_40_,
		_CLAIM_UDF_41_,_CLAIM_UDF_42_,_CLAIM_UDF_43_,_CLAIM_UDF_44_,_CLAIM_UDF_45_,
		_CLAIM_UDF_46_,_CLAIM_UDF_47_,_CLAIM_UDF_48_,_CLAIM_UDF_49_,_CLAIM_UDF_50_,

		_CLAIM_UDF_51_,_CLAIM_UDF_52_,_CLAIM_UDF_53_,_CLAIM_UDF_54_,_CLAIM_UDF_55_,
		_CLAIM_UDF_56_,_CLAIM_UDF_57_,_CLAIM_UDF_58_,_CLAIM_UDF_59_,_CLAIM_UDF_60_,
		_CLAIM_UDF_61_,_CLAIM_UDF_62_,_CLAIM_UDF_63_,_CLAIM_UDF_64_,_CLAIM_UDF_65_,
		_CLAIM_UDF_66_,_CLAIM_UDF_67_,_CLAIM_UDF_68_,_CLAIM_UDF_69_,_CLAIM_UDF_70_,
		_CLAIM_UDF_71_,_CLAIM_UDF_72_,_CLAIM_UDF_73_,_CLAIM_UDF_74_,_CLAIM_UDF_75_,
		_CLAIM_UDF_76_,_CLAIM_UDF_77_,_CLAIM_UDF_78_,_CLAIM_UDF_79_,_CLAIM_UDF_80_,
		_CLAIM_UDF_81_,_CLAIM_UDF_82_,_CLAIM_UDF_83_,_CLAIM_UDF_84_,_CLAIM_UDF_85_,
		_CLAIM_UDF_86_,_CLAIM_UDF_87_,_CLAIM_UDF_88_,_CLAIM_UDF_89_,_CLAIM_UDF_90_,
		_CLAIM_UDF_91_,_CLAIM_UDF_92_,_CLAIM_UDF_93_,_CLAIM_UDF_94_,_CLAIM_UDF_95_,
		_CLAIM_UDF_96_,_CLAIM_UDF_97_,_CLAIM_UDF_98_,_CLAIM_UDF_99_,_CLAIM_UDF_100_
		)
	SELECT 
		S.SERVICE_MONTH_START_DATE,
		CI.T_CLAIM_ID_KEY AS CLAIM_ID_KEY,
		K.T_SERVICES_KEY AS SERVICES_KEY,
		S.MI_POST_DATE,
		_CLAIM_UDF_01_,_CLAIM_UDF_02_,_CLAIM_UDF_03_,_CLAIM_UDF_04_,_CLAIM_UDF_05_,
		_CLAIM_UDF_06_,_CLAIM_UDF_07_,_CLAIM_UDF_08_,_CLAIM_UDF_09_,_CLAIM_UDF_10_,
		_CLAIM_UDF_11_,_CLAIM_UDF_12_,_CLAIM_UDF_13_,_CLAIM_UDF_14_,_CLAIM_UDF_15_,
		_CLAIM_UDF_16_,_CLAIM_UDF_17_,_CLAIM_UDF_18_,_CLAIM_UDF_19_,_CLAIM_UDF_20_,
		_CLAIM_UDF_21_,_CLAIM_UDF_22_,_CLAIM_UDF_23_,_CLAIM_UDF_24_,_CLAIM_UDF_25_,
		_CLAIM_UDF_26_,_CLAIM_UDF_27_,_CLAIM_UDF_28_,_CLAIM_UDF_29_,_CLAIM_UDF_30_,
		_CLAIM_UDF_31_,_CLAIM_UDF_32_,_CLAIM_UDF_33_,_CLAIM_UDF_34_,_CLAIM_UDF_35_,
		_CLAIM_UDF_36_,_CLAIM_UDF_37_,_CLAIM_UDF_38_,_CLAIM_UDF_39_,_CLAIM_UDF_40_,
		_CLAIM_UDF_41_,_CLAIM_UDF_42_,_CLAIM_UDF_43_,_CLAIM_UDF_44_,_CLAIM_UDF_45_,
		_CLAIM_UDF_46_,_CLAIM_UDF_47_,_CLAIM_UDF_48_,_CLAIM_UDF_49_,_CLAIM_UDF_50_,
		_CLAIM_UDF_51_,_CLAIM_UDF_52_,_CLAIM_UDF_53_,_CLAIM_UDF_54_,_CLAIM_UDF_55_,
		_CLAIM_UDF_56_,_CLAIM_UDF_57_,_CLAIM_UDF_58_,_CLAIM_UDF_59_,_CLAIM_UDF_60_,
		_CLAIM_UDF_61_,_CLAIM_UDF_62_,_CLAIM_UDF_63_,_CLAIM_UDF_64_,_CLAIM_UDF_65_,
		_CLAIM_UDF_66_,_CLAIM_UDF_67_,_CLAIM_UDF_68_,_CLAIM_UDF_69_,_CLAIM_UDF_70_,
		_CLAIM_UDF_71_,_CLAIM_UDF_72_,_CLAIM_UDF_73_,_CLAIM_UDF_74_,_CLAIM_UDF_75_,
		_CLAIM_UDF_76_,_CLAIM_UDF_77_,_CLAIM_UDF_78_,_CLAIM_UDF_79_,_CLAIM_UDF_80_,
		_CLAIM_UDF_81_,_CLAIM_UDF_82_,_CLAIM_UDF_83_,_CLAIM_UDF_84_,_CLAIM_UDF_85_,
		_CLAIM_UDF_86_,_CLAIM_UDF_87_,_CLAIM_UDF_88_,_CLAIM_UDF_89_,_CLAIM_UDF_90_,
		_CLAIM_UDF_91_,_CLAIM_UDF_92_,_CLAIM_UDF_93_,_CLAIM_UDF_94_,_CLAIM_UDF_95_,
		_CLAIM_UDF_96_,_CLAIM_UDF_97_,_CLAIM_UDF_98_,_CLAIM_UDF_99_,_CLAIM_UDF_100_
	FROM ' + @DB_NAME + '.DBO.SERVICES_UDF S
		LEFT JOIN CST.CONSOLIDATE_SERVICEKEY K ON K.CID = '''+@CID + ''' AND S.SERVICES_KEY = K.S_SERVICES_KEY
		LEFT JOIN ##RFT_CLAIM_ID CI ON S.CLAIM_ID_KEY = CI.S_CLAIM_ID_KEY '
		
	EXECUTE(@SQL)

	SET @SQL = 'SERVICES_UDF read and consolidated from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait


	SET @SQL = '
	INSERT INTO SERVICES_RX(
		SERVICE_MONTH_START_DATE,
		MEMBER_KEY,
		FROM_DATE,
		CLAIM_ID_KEY,
		SERVICES_KEY,
		MI_POST_DATE,
		NDC_KEY,
		RX_THER_CLASS_KEY,
		RX_DAYS_SUPPLY,
		RX_DRUG_COST,
		RX_INGR_COST,
		RX_DISP_FEE,
		RX_DISCOUNT,
		RX_DAW,
		RX_FILL_SRC,
		RX_REFILLS,
		RX_PAR,
		RX_FORM,
		NDC_SCD_KEY
		)
	SELECT
		SRX.SERVICE_MONTH_START_DATE AS INCURRED_MONTH_START_DATE,
		M.T_MEMBER_KEY,
		SRX.FROM_DATE,
		CI.T_CLAIM_ID_KEY AS CLAIM_ID_KEY,
		K.T_SERVICES_KEY AS SERVICES_KEY,
		SRX.MI_POST_DATE,
		COALESCE(T_NDC_KEY,0) AS NDC_KEY,
		COALESCE(N.RX_THER_CLASS_KEY,0) AS RX_THER_CLASS_KEY,
		RX_DAYS_SUPPLY,
		RX_DRUG_COST,
		RX_INGR_COST,
		RX_DISP_FEE,
		RX_DISCOUNT,
		RX_DAW,
		RX_FILL_SRC,
		RX_REFILLS,
		RX_PAR,
		RX_FORM,
		NDC_SCD_KEY
	FROM ' + @DB_NAME + '.DBO.SERVICES_RX SRX
		LEFT JOIN CST.CONSOLIDATE_SERVICEKEY K ON K.CID = '''+@CID + ''' AND SRX.SERVICES_KEY = K.S_SERVICES_KEY
		LEFT JOIN ##MEMBER M ON SRX.MEMBER_KEY = M.S_MEMBER_KEY
		LEFT JOIN ##RFT_CLAIM_ID CI ON SRX.CLAIM_ID_KEY = CI.S_CLAIM_ID_KEY
		LEFT JOIN ##RFT_NDC N ON SRX.NDC_KEY = N.S_NDC_KEY '
		
	EXECUTE(@SQL)

	SET @SQL = 'SERVICES_RX read and consolidated from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait
	
	SET @SQL = '
	INSERT INTO SERVICES_WASTE(
		SERVICE_MONTH_START_DATE,
		CLAIM_ID_KEY,
		SERVICES_KEY,
		MI_POST_DATE,
		WASTE_SERVICE_ID,
		WASTE_CAT_KEY,
		WASTE_SERVICE_COUNT_FLAG,
		DEGREE_OF_CERTAINTY,
		LINE_TYPE,
		SUFFICIENT_HISTORY_FLAG,
		PREVALENCE_RANK
		)
	SELECT 
		S.SERVICE_MONTH_START_DATE,
		CI.T_CLAIM_ID_KEY AS CLAIM_ID_KEY,
		K.T_SERVICES_KEY AS SERVICES_KEY,
		S.MI_POST_DATE,
		WASTE_SERVICE_ID,
		WASTE_CAT_KEY,
		WASTE_SERVICE_COUNT_FLAG,
		DEGREE_OF_CERTAINTY,
		LINE_TYPE,
		SUFFICIENT_HISTORY_FLAG,
		PREVALENCE_RANK
	FROM ' + @DB_NAME + '.DBO.SERVICES_WASTE S
		LEFT JOIN CST.CONSOLIDATE_SERVICEKEY K ON K.CID = '''+@CID + ''' AND S.WASTE_SERVICE_ID = K.S_SERVICES_KEY
		LEFT JOIN ##RFT_CLAIM_ID CI ON S.CLAIM_ID_KEY = CI.S_CLAIM_ID_KEY
		where k.T_SERVICES_KEY is not null '
	--PRINT (@SQL)	
	EXECUTE(@SQL)

	SET @SQL = 'SERVICES_WASTE read and consolidated from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait
	
	
	SET @SQL = '
	exec sp_mi_droptable ''##SERVICES_UB''
	SELECT 
		S.SERVICE_MONTH_START_DATE AS INCURRED_MONTH_START_DATE,
		CI.T_CLAIM_ID_KEY AS CLAIM_ID_KEY,
		S.SERVICES_KEY,
		S.MI_POST_DATE,
		M.T_MEMBER_KEY,
		SUB.FROM_DATE,
		ADM_DATE,
		ADM_TYPE,
		ADM_SRC,
		DIS_DATE,
		CLIENT_LOS,
		HOSP_TYPE,
		MS.DRG_CODE AS MS_DRG_CODE,
		AP.DRG_CODE AS AP_DRG_CODE,
		APR.DRG_CODE AS APR_DRG_CODE,
		APR_DRG_SEV,
		MIMS.DRG_CODE AS MI_MS_DRG_CODE,
		MIAP.DRG_CODE AS MI_AP_DRG_CODE,
		MIAPR.DRG_CODE AS MI_APR_DRG_CODE,
		MI_APR_DRG_SEV,
		IP01.ICD_PROC AS ICD_PROC_01,
		IP02.ICD_PROC AS ICD_PROC_02,
		IP03.ICD_PROC AS ICD_PROC_03,
		IP04.ICD_PROC AS ICD_PROC_04,
		IP05.ICD_PROC AS ICD_PROC_05,
		IP06.ICD_PROC AS ICD_PROC_06,
		IP07.ICD_PROC AS ICD_PROC_07,
		IP08.ICD_PROC AS ICD_PROC_08,
		IP09.ICD_PROC AS ICD_PROC_09,
		IP10.ICD_PROC AS ICD_PROC_10,
		IP11.ICD_PROC AS ICD_PROC_11,
		IP12.ICD_PROC AS ICD_PROC_12,
		IP13.ICD_PROC AS ICD_PROC_13,
		IP14.ICD_PROC AS ICD_PROC_14,
		IP15.ICD_PROC AS ICD_PROC_15,
		IP16.ICD_PROC AS ICD_PROC_16,
		UB_BILL_TYPE,
		REV_CODE,
		DIS_STAT,
		BABY_WGHT,
		WEEKS_GEST,
		BABY_CLAIM_ID_KEY,
		PSC_KEY,
		TR.DRG_CODE AS TRI_DRG_CODE,
		MITR.DRG_CODE AS MI_TRI_DRG_CODE,
		DATA_SOURCE
	INTO ##SERVICES_UB
	FROM ' + @DB_NAME + '.DBO.SERVICES S
		INNER JOIN ' + @DB_NAME + '.DBO.SERVICES_UB SUB
			ON 	S.SERVICE_MONTH_START_DATE=SUB.SERVICE_MONTH_START_DATE 
			AND S.CLAIM_ID_KEY = SUB.CLAIM_ID_KEY 
			AND S.SERVICES_KEY = SUB.SERVICES_KEY 
			AND S.MI_POST_DATE = SUB.MI_POST_DATE
		LEFT JOIN ' + @DB_NAME + '.DBO.SERVICES_2 S2
			ON 	S.SERVICE_MONTH_START_DATE=S2.SERVICE_MONTH_START_DATE 
			AND S.CLAIM_ID_KEY = S2.CLAIM_ID_KEY 
			AND S.SERVICES_KEY = S2.SERVICES_KEY 
			AND S.MI_POST_DATE = S2.MI_POST_DATE
		LEFT JOIN ##MEMBER M ON S.MEMBER_KEY = M.S_MEMBER_KEY
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DATA_SOURCE D ON S2.CL_DATA_SRC_KEY = D.DATA_SOURCE_KEY
		LEFT JOIN ##RFT_CLAIM_ID CI ON S.CLAIM_ID_KEY = CI.S_CLAIM_ID_KEY
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ADM_TYPE AT ON SUB.ADM_TYPE_KEY = AT.ADM_TYPE_KEY
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ADM_SRC AR ON SUB.ADM_SRC_KEY = AR.ADM_SRC_KEY
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DRG MS ON SUB.MS_DRG_KEY = MS.DRG_KEY AND MS.DRG_TYPE = ''MS''
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DRG AP ON SUB.AP_DRG_KEY = AP.DRG_KEY AND AP.DRG_TYPE = ''AP''
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DRG APR ON SUB.APR_DRG_KEY = APR.DRG_KEY AND APR.DRG_TYPE = ''APR''
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DRG TR ON SUB.TRI_DRG_KEY = TR.DRG_KEY AND TR.DRG_TYPE = ''TRI''
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DRG MIMS ON SUB.MI_MS_DRG_KEY = MIMS.DRG_KEY AND MIMS.DRG_TYPE = ''MS''
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DRG MIAP ON SUB.MI_AP_DRG_KEY = MIAP.DRG_KEY AND MIAP.DRG_TYPE = ''AP''
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DRG MIAPR ON SUB.MI_APR_DRG_KEY = MIAPR.DRG_KEY AND MIAPR.DRG_TYPE = ''APR''	
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DRG MITR ON SUB.MI_TRI_DRG_KEY = MITR.DRG_KEY AND TR.DRG_TYPE = ''TRI''
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP01 ON SUB.ICD_PROC_01_KEY = IP01.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP02 ON SUB.ICD_PROC_02_KEY = IP02.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP03 ON SUB.ICD_PROC_03_KEY = IP03.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP04 ON SUB.ICD_PROC_04_KEY = IP04.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP05 ON SUB.ICD_PROC_05_KEY = IP05.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP06 ON SUB.ICD_PROC_06_KEY = IP06.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP07 ON SUB.ICD_PROC_07_KEY = IP07.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP08 ON SUB.ICD_PROC_08_KEY = IP08.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP09 ON SUB.ICD_PROC_09_KEY = IP09.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP10 ON SUB.ICD_PROC_10_KEY = IP10.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP11 ON SUB.ICD_PROC_11_KEY = IP11.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP12 ON SUB.ICD_PROC_12_KEY = IP12.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP13 ON SUB.ICD_PROC_13_KEY = IP13.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP14 ON SUB.ICD_PROC_14_KEY = IP14.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP15 ON SUB.ICD_PROC_15_KEY = IP15.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_ICD_PROC IP16 ON SUB.ICD_PROC_16_KEY = IP16.ICD_PROC_KEY 
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_UB_BILL_TYPE UBT ON SUB.UBBILL_TYPE_KEY = UBT.UB_BILL_TYPE_KEY
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_REV_CODE R ON SUB.REV_CODE_KEY = R.REV_CODE_KEY
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DIS_STAT DS ON SUB.DIS_STAT_KEY = DS.DIS_STAT_KEY
		LEFT JOIN ' + @DB_NAME + '.DBO.RFT_DATES DT ON S.SERVICE_MONTH_START_DATE=DT.DATES  '
		
	EXECUTE(@SQL)

	SET @SQL = 'SERVICES_UB read from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait
	
		
	-- SERVICES_UB --
	SET @SQL = '
	INSERT INTO SERVICES_UB(
		SERVICE_MONTH_START_DATE,
		MEMBER_KEY,
		FROM_DATE,
		CLAIM_ID_KEY,
		SERVICES_KEY,
		MI_POST_DATE,
		ADM_DATE,
		ADM_TYPE_KEY,
		ADM_SRC_KEY,
		DIS_DATE,
		CLIENT_LOS,
		HOSP_TYPE,
		MS_DRG_KEY,
		AP_DRG_KEY,
		APR_DRG_KEY,
		APR_DRG_SEV,
		MI_MS_DRG_KEY,
		MI_AP_DRG_KEY,
		MI_APR_DRG_KEY,
		MI_APR_DRG_SEV,
		ICD_PROC_01_KEY,ICD_PROC_02_KEY,ICD_PROC_03_KEY,ICD_PROC_04_KEY,ICD_PROC_05_KEY,
		ICD_PROC_06_KEY,ICD_PROC_07_KEY,ICD_PROC_08_KEY,ICD_PROC_09_KEY,ICD_PROC_10_KEY,
		ICD_PROC_11_KEY,ICD_PROC_12_KEY,ICD_PROC_13_KEY,ICD_PROC_14_KEY,ICD_PROC_15_KEY,ICD_PROC_16_KEY,
		UBBILL_TYPE_KEY,
		REV_CODE_KEY,
		DIS_STAT_KEY,
		BABY_WGHT,
		WEEKS_GEST,
		BABY_CLAIM_ID_KEY,
		PSC_KEY,
		TRI_DRG_KEY,
		MI_TRI_DRG_KEY,
		ICD_PROC_17_KEY,ICD_PROC_18_KEY,ICD_PROC_19_KEY,ICD_PROC_20_KEY,ICD_PROC_21_KEY,
		ICD_PROC_22_KEY,ICD_PROC_23_KEY,ICD_PROC_24_KEY,ICD_PROC_25_KEY,ICD_PROC_26_KEY,
		ICD_PROC_27_KEY,ICD_PROC_28_KEY,ICD_PROC_29_KEY,ICD_PROC_30_KEY
		)
	SELECT
		C.INCURRED_MONTH_START_DATE AS SERVICE_MONTH_START_DATE,
		C.T_MEMBER_KEY,
		C.FROM_DATE,
		COALESCE(C.CLAIM_ID_KEY,0) AS CLAIM_ID_KEY,
		K.T_SERVICES_KEY AS SERVICES_KEY,
		C.MI_POST_DATE,
		ADM_DATE,
		COALESCE(ADM_TYPE_KEY,0),
		COALESCE(ADM_SRC_KEY,0),
		DIS_DATE,
		COALESCE(CLIENT_LOS,0),
		HOSP_TYPE,
		COALESCE(MS.DRG_KEY,0),
		COALESCE(AP.DRG_KEY,0),
		COALESCE(APR.DRG_KEY,0),
		APR_DRG_SEV,
		COALESCE(MIMS.DRG_KEY,0),
		COALESCE(MIAP.DRG_KEY,0),
		COALESCE(MIAPR.DRG_KEY,0),
		MI_APR_DRG_SEV,
		COALESCE(IP01.ICD_PROC_KEY,0) AS ICD_PROC_01_KEY,
		COALESCE(IP02.ICD_PROC_KEY,0) AS ICD_PROC_02_KEY,
		COALESCE(IP03.ICD_PROC_KEY,0) AS ICD_PROC_03_KEY,
		COALESCE(IP04.ICD_PROC_KEY,0) AS ICD_PROC_04_KEY,
		COALESCE(IP05.ICD_PROC_KEY,0) AS ICD_PROC_05_KEY,
		COALESCE(IP06.ICD_PROC_KEY,0) AS ICD_PROC_06_KEY,
		COALESCE(IP07.ICD_PROC_KEY,0) AS ICD_PROC_07_KEY,
		COALESCE(IP08.ICD_PROC_KEY,0) AS ICD_PROC_08_KEY,
		COALESCE(IP09.ICD_PROC_KEY,0) AS ICD_PROC_09_KEY,
		COALESCE(IP10.ICD_PROC_KEY,0) AS ICD_PROC_10_KEY,
		COALESCE(IP11.ICD_PROC_KEY,0) AS ICD_PROC_11_KEY,
		COALESCE(IP12.ICD_PROC_KEY,0) AS ICD_PROC_12_KEY,
		COALESCE(IP13.ICD_PROC_KEY,0) AS ICD_PROC_13_KEY,
		COALESCE(IP14.ICD_PROC_KEY,0) AS ICD_PROC_14_KEY,
		COALESCE(IP15.ICD_PROC_KEY,0) AS ICD_PROC_15_KEY,
		COALESCE(IP16.ICD_PROC_KEY,0) AS ICD_PROC_16_KEY,
		COALESCE(UBT.UB_BILL_TYPE_KEY,0) AS UB_BILL_TYPE_KEY,
		COALESCE(R.REV_CODE_KEY,0) AS REV_CODE_KEY,
		COALESCE(DS.DIS_STAT_KEY,0) AS DIS_STAT_KEY,
		BABY_WGHT,
		WEEKS_GEST,
		0 AS BABY_CLAIM_ID_KEY,
		COALESCE(PSC_KEY,0) AS PSC_KEY,
		COALESCE(TR.DRG_KEY,0) AS TR_DRG_KEY,
		COALESCE(MITR.DRG_KEY,0) AS MI_TR_DRG_KEY,
		0 AS ICD_PROC_17_KEY,0 AS ICD_PROC_18_KEY,0 AS ICD_PROC_19_KEY,0 AS ICD_PROC_20_KEY,
		0 AS ICD_PROC_21_KEY,0 AS ICD_PROC_22_KEY,0 AS ICD_PROC_23_KEY,0 AS ICD_PROC_24_KEY,
		0 AS ICD_PROC_25_KEY,0 AS ICD_PROC_26_KEY,0 AS ICD_PROC_27_KEY,0 AS ICD_PROC_28_KEY,
		0 AS ICD_PROC_29_KEY,0 AS ICD_PROC_30_KEY
	FROM ##SERVICES_UB C
		LEFT JOIN CST.CONSOLIDATE_SERVICEKEY K ON K.CID = '''+@CID + ''' AND C.SERVICES_KEY = K.S_SERVICES_KEY
		LEFT JOIN RFT_ADM_TYPE AT ON C.ADM_TYPE = AT.ADM_TYPE
		LEFT JOIN RFT_ADM_SRC AR ON C.ADM_SRC = AR.ADM_SRC
		LEFT JOIN RFT_DRG MS ON C.MS_DRG_CODE = MS.DRG_CODE AND MS.DRG_TYPE = ''MS''
		LEFT JOIN RFT_DRG AP ON C.AP_DRG_CODE = AP.DRG_CODE AND AP.DRG_TYPE = ''AP''
		LEFT JOIN RFT_DRG APR ON C.APR_DRG_CODE = APR.DRG_CODE AND APR.DRG_TYPE = ''APR''
		LEFT JOIN RFT_DRG TR ON C.TRI_DRG_CODE = TR.DRG_CODE AND TR.DRG_TYPE = ''TRI''
		LEFT JOIN RFT_DRG MIMS ON C.MI_MS_DRG_CODE = MIMS.DRG_CODE AND MIMS.DRG_TYPE = ''MS''
		LEFT JOIN RFT_DRG MIAP ON C.MI_AP_DRG_CODE = MIAP.DRG_CODE AND MIAP.DRG_TYPE = ''AP''
		LEFT JOIN RFT_DRG MIAPR ON C.MI_APR_DRG_CODE = MIAPR.DRG_CODE AND MIAPR.DRG_TYPE = ''APR''	
		LEFT JOIN RFT_DRG MITR ON C.MI_TRI_DRG_CODE = MITR.DRG_CODE AND MITR.DRG_TYPE = ''TRI''
		LEFT JOIN RFT_ICD_PROC IP01 ON C.ICD_PROC_01 = IP01.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP02 ON C.ICD_PROC_02 = IP02.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP03 ON C.ICD_PROC_03 = IP03.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP04 ON C.ICD_PROC_04 = IP04.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP05 ON C.ICD_PROC_05 = IP05.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP06 ON C.ICD_PROC_06 = IP06.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP07 ON C.ICD_PROC_07 = IP07.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP08 ON C.ICD_PROC_08 = IP08.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP09 ON C.ICD_PROC_09 = IP09.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP10 ON C.ICD_PROC_10 = IP10.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP11 ON C.ICD_PROC_11 = IP11.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP12 ON C.ICD_PROC_12 = IP12.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP13 ON C.ICD_PROC_13 = IP13.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP14 ON C.ICD_PROC_14 = IP14.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP15 ON C.ICD_PROC_15 = IP15.ICD_PROC 
		LEFT JOIN RFT_ICD_PROC IP16 ON C.ICD_PROC_16 = IP16.ICD_PROC 
		LEFT JOIN RFT_UB_BILL_TYPE UBT ON C.UB_BILL_TYPE = UBT.UB_BILL_TYPE
		LEFT JOIN RFT_REV_CODE R ON C.REV_CODE = R.REV_CODE
		LEFT JOIN RFT_DIS_STAT DS ON C.DIS_STAT = DS.DIS_STAT '
	EXECUTE(@SQL)

	exec sp_mi_droptable '##SERVICES_UB'
	SET @SQL = 'Created SERVICES_UB from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait

SET @SQL = 'INSERT INTO SERVICES_ETG 
([SERVICE_MONTH_START_DATE]
      ,[CLAIM_ID_KEY]
      ,[SERVICES_KEY]
      ,[MI_POST_DATE]
      ,[ETG_KEY]
      ,[ETG_SEVERITY]
      ,[ETG_EPISODE_NUMBER]
      ,[ETG_MAX_INCURRED_MONTH_START_DATE]
      ,[ETG_CLUSTER_NUMBER]
      ,[ETG_EPISODE_TYPE]
      ,[ETG_USER_EPISODE_TYPE]
      ,[ETG_RECORD_TYPE]
      ,[ETG_CLUSTER_PROVIDER_KEY]
      ,[ETG_DRUG_CLASS_CODE]
      ,[ETG_INTERNAL_PROVIDER_TYPE]
      ,[ETG_INTERNAL_SERVICE_TYPE]
      ,[ETG_CONFINEMENT_NUMBER]
      ,[ETG_GROUPER_VERSION]
      ,[ETG_PHANTOM]
      ,[ETG_ANCILLARY_TYPE]
      ,[ETG_OUTLIER_STATUS]
      ,[ETG_USER_OUTLIER_STATUS]
      ,[ETG_MEDICAL_CLAIM_TYPE]
      ,[LAST_GROUPING]
      ,[ETG_MIN_INCURRED_MONTH_START_DATE]
      ,[ETG_EPISODE_COUNT_ALLOWED_PRORATE]
      ,[ETG_EPISODE_COUNT_PAID_PRORATE]
      ,[ETG_EPISODE_MONTHS_DURATION]
      ,[ETG_EPISODE_DAYS_DURATION])
	  SELECT 
	  	S.SERVICE_MONTH_START_DATE
	  ,CI.T_CLAIM_ID_KEY AS CLAIM_ID_KEY
	  ,K.T_SERVICES_KEY AS SERVICES_KEY
	  ,S.MI_POST_DATE
      ,[ETG_KEY]
      ,[ETG_SEVERITY]
      ,[ETG_EPISODE_NUMBER]
      ,[ETG_MAX_INCURRED_MONTH_START_DATE]
      ,[ETG_CLUSTER_NUMBER]
      ,[ETG_EPISODE_TYPE]
      ,[ETG_USER_EPISODE_TYPE]
      ,[ETG_RECORD_TYPE]
      ,AP.T_PROV_KEY AS [ETG_CLUSTER_PROVIDER_KEY]
      ,[ETG_DRUG_CLASS_CODE]
      ,[ETG_INTERNAL_PROVIDER_TYPE]
      ,[ETG_INTERNAL_SERVICE_TYPE]
      ,[ETG_CONFINEMENT_NUMBER]
      ,[ETG_GROUPER_VERSION]
      ,[ETG_PHANTOM]
      ,[ETG_ANCILLARY_TYPE]
      ,[ETG_OUTLIER_STATUS]
      ,[ETG_USER_OUTLIER_STATUS]
      ,[ETG_MEDICAL_CLAIM_TYPE]
      ,[LAST_GROUPING]
      ,[ETG_MIN_INCURRED_MONTH_START_DATE]
      ,[ETG_EPISODE_COUNT_ALLOWED_PRORATE]
      ,[ETG_EPISODE_COUNT_PAID_PRORATE]
      ,[ETG_EPISODE_MONTHS_DURATION]
      ,[ETG_EPISODE_DAYS_DURATION]
	  	FROM ' + @DB_NAME + '.DBO.SERVICES_ETG S
		LEFT JOIN CST.CONSOLIDATE_SERVICEKEY K ON K.CID = '''+@CID + ''' AND S.SERVICES_KEY = K.S_SERVICES_KEY
		LEFT JOIN ##PROVIDER AP ON S.ETG_CLUSTER_PROVIDER_KEY = AP.S_PROV_KEY 
		LEFT JOIN ##RFT_CLAIM_ID CI ON S.CLAIM_ID_KEY = CI.S_CLAIM_ID_KEY '

    PRINT (@SQL)
	EXECUTE(@SQL)

		SET @SQL = 'Created SERVICES_ETG from ' + @DB_NAME
	raiserror (@SQL, 10,1) with nowait



	FETCH NEXT FROM db_cursor INTO @DB_NAME,@CID
	
END 

CLOSE db_cursor   
DEALLOCATE db_cursor 

IF @INDEX = 'Y' BEGIN
	exec SP_MI_TOGGLE_IDX 'SERVICES_UDF','ON'
	exec SP_MI_TOGGLE_IDX 'SERVICES_2','OFF'
	exec SP_MI_TOGGLE_IDX 'SERVICES','ON'
	exec SP_MI_TOGGLE_IDX 'SERVICES_UB','ON'
	exec SP_MI_TOGGLE_IDX 'SERVICES_RX','ON'
	exec SP_MI_TOGGLE_IDX 'SERVICES_WASTE','ON'
	exec SP_MI_TOGGLE_IDX 'SERVICES_ETG','ON'

END






GO


